//! `panschema.lock` — pinned schema dependencies with content checksums.
//!
//! Generated by `panschema fetch`, verified by `panschema verify`. Committed
//! alongside `panschema.toml` to make codegen reproducible: a build that
//! passed once, with a particular schema content, can be re-run with
//! confidence that the inputs haven't drifted.
//!
//! Reference: [`docs/features/05-schema-manager.md`](../../docs/features/05-schema-manager.md)

use std::path::Path;
use std::str::FromStr;

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

/// Filename used for the lockfile, sibling of `panschema.toml`.
pub const LOCKFILE_FILENAME: &str = "panschema.lock";

#[derive(Debug, thiserror::Error)]
pub enum LockfileError {
    #[error("failed to read lockfile: {0}")]
    Io(#[from] std::io::Error),
    #[error("invalid lockfile: {0}")]
    Parse(#[from] toml::de::Error),
    #[error("failed to serialize lockfile: {0}")]
    Serialize(#[from] toml::ser::Error),
}

/// Top-level structure of `panschema.lock`. Each `[[schema]]` array entry
/// pins one dependency from `panschema.toml`.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
pub struct Lockfile {
    #[serde(default, rename = "schema", skip_serializing_if = "Vec::is_empty")]
    pub entries: Vec<LockEntry>,
}

/// One pinned schema dependency.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LockEntry {
    /// Schema name (matches the dict key in `panschema.toml` `[schemas]`).
    pub name: String,
    /// Version declared in the schema's `panschema-publish.toml`. Fresh
    /// fetches always populate this for both `path:` and `github:` sources;
    /// the field is `Option<String>` to keep older lockfiles (pre-redesign)
    /// readable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    /// Source spec — `path:<rel>` for local packages, `github:owner/repo`
    /// for tagged GitHub commits.
    pub source: String,
    /// Resolved revision (commit SHA for `github:` sources). `None` for
    /// `path:` sources, which have no revision concept.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    /// Content checksum of the schema's main file, e.g. `sha256:abc123…`.
    pub checksum: String,
}

impl FromStr for Lockfile {
    type Err = LockfileError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        Ok(toml::from_str(s)?)
    }
}

impl Lockfile {
    /// Read a lockfile from disk.
    pub fn from_path(path: &Path) -> Result<Self, LockfileError> {
        let content = std::fs::read_to_string(path)?;
        content.parse()
    }

    /// Serialize as TOML.
    pub fn to_toml_string(&self) -> Result<String, LockfileError> {
        Ok(toml::to_string_pretty(self)?)
    }

    /// Write the lockfile to disk in canonical TOML form.
    pub fn write_to_path(&self, path: &Path) -> Result<(), LockfileError> {
        let s = self.to_toml_string()?;
        std::fs::write(path, s)?;
        Ok(())
    }

    /// Look up an entry by schema name.
    pub fn entry(&self, name: &str) -> Option<&LockEntry> {
        self.entries.iter().find(|e| e.name == name)
    }
}

/// Compute the SHA-256 hex digest of a file's content, returned as
/// `sha256:<64-hex>`.
pub fn checksum_file(path: &Path) -> std::io::Result<String> {
    let bytes = std::fs::read(path)?;
    let mut hasher = Sha256::new();
    hasher.update(&bytes);
    Ok(format!("sha256:{}", hex::encode(hasher.finalize())))
}

/// Build a `path:` source spec from a manifest-relative path. The path is
/// stored as-written (not canonicalized) so the lockfile stays portable.
pub fn path_source_spec(rel_path: &Path) -> String {
    format!("path:{}", rel_path.display())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn path_source_spec_emits_exact_prefix_and_path() {
        // The lockfile's `source` field for `path:` entries must round-trip
        // byte-exactly so consumers can match against it (e.g. `verify`
        // detecting that a manifest entry's path stayed the same).
        let s = path_source_spec(Path::new("./schema/my.yaml"));
        assert_eq!(s, "path:./schema/my.yaml");

        // Non-trivial relative path components survive unchanged.
        let s = path_source_spec(Path::new("../sibling/pkg"));
        assert_eq!(s, "path:../sibling/pkg");

        // An empty path produces the bare prefix — degenerate but defined.
        let s = path_source_spec(Path::new(""));
        assert_eq!(s, "path:");
    }

    #[test]
    fn empty_lockfile_round_trips() {
        let original = Lockfile::default();
        let s = original.to_toml_string().expect("serialize");
        let parsed: Lockfile = s.parse().expect("parse");
        assert_eq!(parsed, original);
    }

    #[test]
    fn parses_lockfile_with_one_path_entry() {
        let toml = r#"
[[schema]]
name = "my-local"
source = "path:./schema/my.yaml"
checksum = "sha256:0000000000000000000000000000000000000000000000000000000000000000"
"#;
        let lf: Lockfile = toml.parse().expect("parse");
        assert_eq!(lf.entries.len(), 1);
        let e = &lf.entries[0];
        assert_eq!(e.name, "my-local");
        assert_eq!(e.source, "path:./schema/my.yaml");
        assert_eq!(e.version, None);
        assert_eq!(e.revision, None);
    }

    #[test]
    fn parses_lockfile_with_versioned_github_entry() {
        let toml = r#"
[[schema]]
name = "scimantic-schema"
version = "0.1.3"
source = "github:padamson/scimantic-schema"
revision = "abc123def456"
checksum = "sha256:1111111111111111111111111111111111111111111111111111111111111111"
"#;
        let lf: Lockfile = toml.parse().expect("parse");
        let e = &lf.entries[0];
        assert_eq!(e.version.as_deref(), Some("0.1.3"));
        assert_eq!(e.revision.as_deref(), Some("abc123def456"));
    }

    #[test]
    fn round_trips_multi_entry_lockfile() {
        let original = Lockfile {
            entries: vec![
                LockEntry {
                    name: "a".into(),
                    version: None,
                    source: "path:./a.yaml".into(),
                    revision: None,
                    checksum: "sha256:aaaa".into(),
                },
                LockEntry {
                    name: "b".into(),
                    version: Some("1.0.0".into()),
                    source: "github:x/b".into(),
                    revision: Some("deadbeef".into()),
                    checksum: "sha256:bbbb".into(),
                },
            ],
        };
        let s = original.to_toml_string().expect("serialize");
        let parsed: Lockfile = s.parse().expect("parse");
        assert_eq!(parsed, original);
    }

    #[test]
    fn errors_on_unknown_field_in_entry() {
        let toml = r#"
[[schema]]
name = "x"
source = "path:./x.yaml"
checksum = "sha256:00"
unrecognized = "field"
"#;
        let err = toml.parse::<Lockfile>().expect_err("should reject");
        assert!(matches!(err, LockfileError::Parse(_)));
    }

    #[test]
    fn checksum_file_is_deterministic_and_prefixed() {
        let mut tmp = tempfile::Builder::new()
            .suffix(".yaml")
            .tempfile()
            .expect("temp file");
        use std::io::Write;
        tmp.write_all(b"hello world").expect("write");
        let cs1 = checksum_file(tmp.path()).expect("checksum");
        let cs2 = checksum_file(tmp.path()).expect("checksum");
        assert_eq!(cs1, cs2);
        assert!(cs1.starts_with("sha256:"));
        // Known SHA-256 of "hello world".
        assert_eq!(
            cs1,
            "sha256:b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9"
        );
    }

    #[test]
    fn checksum_changes_when_content_changes() {
        let mut tmp = tempfile::Builder::new()
            .suffix(".yaml")
            .tempfile()
            .expect("temp file");
        use std::io::Write;
        tmp.write_all(b"original").expect("write");
        let cs1 = checksum_file(tmp.path()).expect("checksum");

        // Overwrite content.
        let path = tmp.path().to_path_buf();
        std::fs::write(&path, b"changed").expect("rewrite");
        let cs2 = checksum_file(&path).expect("checksum");
        assert_ne!(cs1, cs2);
    }

    #[test]
    fn entry_lookup_by_name() {
        let lf = Lockfile {
            entries: vec![
                LockEntry {
                    name: "a".into(),
                    version: None,
                    source: "path:./a.yaml".into(),
                    revision: None,
                    checksum: "sha256:aaaa".into(),
                },
                LockEntry {
                    name: "b".into(),
                    version: None,
                    source: "path:./b.yaml".into(),
                    revision: None,
                    checksum: "sha256:bbbb".into(),
                },
            ],
        };
        assert!(lf.entry("a").is_some());
        assert!(lf.entry("b").is_some());
        assert!(lf.entry("c").is_none());
    }
}
