//! Postgres DDL writer
//!
//! Writes the LinkML IR to Postgres `CREATE TABLE` DDL: concrete classes,
//! scalar attributes, enums, and single-valued class references. See
//! `docs/features/24-postgres-ddl-writer.md` for the full design,
//! including constructs not yet covered here.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use crate::io::{IoError, IoResult, Writer};
use crate::linkml::{ClassDefinition, SchemaDefinition};

/// Writer for Postgres DDL (`CREATE TABLE` / `CREATE TYPE`).
pub struct PostgresWriter;

impl PostgresWriter {
    pub fn new() -> Self {
        Self
    }

    /// Render the schema to a complete DDL script.
    pub fn render(&self, schema: &SchemaDefinition) -> String {
        render(schema)
    }
}

impl Default for PostgresWriter {
    fn default() -> Self {
        Self::new()
    }
}

impl Writer for PostgresWriter {
    fn write(&self, schema: &SchemaDefinition, output: &Path) -> IoResult<()> {
        if needs_parent_dir(output) {
            std::fs::create_dir_all(output.parent().unwrap()).map_err(IoError::Io)?;
        }
        std::fs::write(output, self.render(schema)).map_err(IoError::Io)?;
        Ok(())
    }

    fn format_id(&self) -> &str {
        "postgres"
    }
}

/// Whether `output` names a parent directory that might need creating.
/// False for a bare filename with no directory component (`.parent()`
/// there is `Some("")`, not `None`, so the check can't just be
/// `.is_some()`).
fn needs_parent_dir(output: &Path) -> bool {
    output.parent().is_some_and(|p| !p.as_os_str().is_empty())
}

fn render(schema: &SchemaDefinition) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "-- @generated by panschema v{}",
        env!("CARGO_PKG_VERSION")
    )
    .ok();
    writeln!(out, "-- Schema: {}", schema.name).ok();
    writeln!(out).ok();

    for enum_name in referenced_enums(schema) {
        let def = &schema.enums[enum_name];
        let type_name = crate::rust_writer::snake_case(enum_name);
        let values: Vec<String> = def
            .permissible_values
            .keys()
            .map(|v| format!("'{}'", v.replace('\'', "''")))
            .collect();
        writeln!(
            out,
            "CREATE TYPE {type_name} AS ENUM ({});",
            values.join(", ")
        )
        .ok();
    }
    writeln!(out).ok();

    // Foreign-key constraints are deferred: added via `ALTER TABLE` after
    // every `CREATE TABLE`, so declaration order (and cycles between
    // classes) never matter — the script still applies in one pass.
    let mut fk_constraints = Vec::new();
    let skips = compute_skips(schema);

    for (class_name, class) in &schema.classes {
        if class.r#abstract {
            // Not meant to be instantiated — nothing to hold a row.
            continue;
        }
        if skips.contains_key(class_name) {
            // Not yet supported (is_a / multivalued / any_of / references
            // a skipped class) — see `skipped_classes` for the diagnostic
            // surfaced to the caller.
            continue;
        }
        let table = crate::rust_writer::snake_case(class_name);
        let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
        let (pk_col, pk_type) = class_primary_key(class, schema);

        // The identifier-marked slot (if any) becomes the primary key
        // column instead of a synthetic one.
        let pk_slot = effective
            .iter()
            .find(|(_, slot)| slot.identifier)
            .map(|(name, _)| name.clone());

        writeln!(out, "CREATE TABLE {table} (").ok();
        let mut lines = vec![format!(
            "    {pk_col} {pk_type} PRIMARY KEY{}",
            if pk_slot.is_none() {
                " DEFAULT gen_random_uuid()"
            } else {
                ""
            }
        )];
        // Slot name → the column name it actually resolves to, so a
        // table-level `unique_keys` constraint (below) can name the real
        // columns — an FK slot's column is `{slot}_{target_pk}`, not the
        // bare slot name, and the identifier slot maps to `pk_col`.
        let mut slot_columns: BTreeMap<&str, String> = BTreeMap::new();
        if let Some(pk) = &pk_slot {
            slot_columns.insert(pk.as_str(), pk_col.clone());
        }
        for (slot_name, slot) in &effective {
            if pk_slot.as_deref() == Some(slot_name.as_str()) {
                continue;
            }
            let not_null = if slot.required { " NOT NULL" } else { "" };
            let range = slot.range.as_deref();
            if let Some(target_class) = range.and_then(|r| schema.classes.get_key_value(r)) {
                let (target_name, target_def) = target_class;
                let (target_pk_col, target_pk_type) = class_primary_key(target_def, schema);
                // Named after the target's actual primary key column
                // (matching LinkML's own relmodel_transformer convention)
                // rather than a hardcoded `_id` suffix, which wouldn't
                // even refer to a real column when the target's key is
                // named something else (e.g. an `identifier` slot `code`).
                let col = format!(
                    "{}_{}",
                    crate::rust_writer::snake_case(slot_name),
                    target_pk_col
                );
                lines.push(format!("    {col} {target_pk_type}{not_null}"));
                fk_constraints.push(FkConstraint {
                    from_table: table.clone(),
                    from_col: col.clone(),
                    to_table: crate::rust_writer::snake_case(target_name),
                    to_col: target_pk_col,
                    constraint_name: format!(
                        "{table}_{}_fkey",
                        crate::rust_writer::snake_case(slot_name)
                    ),
                });
                slot_columns.insert(slot_name.as_str(), col);
            } else {
                let col = crate::rust_writer::snake_case(slot_name);
                let sql_type = sql_type_for_slot_range(range, schema);
                let checks = column_checks(&col, slot);
                lines.push(format!("    {col} {sql_type}{not_null}{checks}"));
                slot_columns.insert(slot_name.as_str(), col);
            }
        }
        // Table-level UNIQUE constraints from `unique_keys`. A key that
        // names a slot the class doesn't have is dropped entirely rather
        // than emitting a UNIQUE over a nonexistent column — the same
        // gap `diagnostics::unresolved_unique_key_slots` warns about on
        // the CLI path, enforced here so the writer never emits broken
        // DDL even if that warning is ignored.
        for (key_name, key) in &class.unique_keys {
            let cols: Option<Vec<&String>> = key
                .unique_key_slots
                .iter()
                .map(|s| slot_columns.get(s.as_str()))
                .collect();
            if let Some(cols) = cols {
                let col_list = cols
                    .iter()
                    .map(|c| c.as_str())
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!(
                    "    CONSTRAINT {table}_{}_key UNIQUE ({col_list})",
                    crate::rust_writer::snake_case(key_name)
                ));
            }
        }
        writeln!(out, "{}", lines.join(",\n")).ok();
        writeln!(out, ");").ok();
        writeln!(out).ok();
    }

    for fk in &fk_constraints {
        writeln!(
            out,
            "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({});",
            fk.from_table, fk.constraint_name, fk.from_col, fk.to_table, fk.to_col
        )
        .ok();
    }

    out
}

/// Inline `CHECK` clauses for a scalar column, from the slot's value
/// constraints — the leading-space-prefixed suffix appended to the column
/// definition. Empty when the slot has none.
///
/// - `pattern` → `CHECK (col ~ 'regex')` (single quotes doubled so the
///   literal can't break the statement, same escaping the enum values use).
/// - `minimum_value` / `maximum_value` → a single `CHECK` combining both
///   with `AND` when both are set, or just the one side when only one is.
fn column_checks(col: &str, slot: &crate::linkml::SlotDefinition) -> String {
    let mut checks = String::new();
    if let Some(p) = &slot.pattern {
        checks.push_str(&format!(" CHECK ({col} ~ '{}')", p.replace('\'', "''")));
    }
    let bound = match (slot.minimum_value, slot.maximum_value) {
        (Some(min), Some(max)) => Some(format!("{col} >= {min} AND {col} <= {max}")),
        (Some(min), None) => Some(format!("{col} >= {min}")),
        (None, Some(max)) => Some(format!("{col} <= {max}")),
        (None, None) => None,
    };
    if let Some(b) = bound {
        checks.push_str(&format!(" CHECK ({b})"));
    }
    checks
}

/// A deferred foreign-key constraint, added after every table is declared.
struct FkConstraint {
    from_table: String,
    from_col: String,
    to_table: String,
    to_col: String,
    constraint_name: String,
}

/// A class this writer doesn't project to a table, and why.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkippedClass {
    pub class: String,
    pub reason: String,
}

/// Classes [`render`] skips, with a diagnostic naming why — `is_a`,
/// a multivalued slot, an `any_of` slot, or a class-range slot that
/// targets one of those (which would otherwise emit a foreign key to a
/// table that's never created), are all not yet supported. An abstract
/// class isn't reported here — it's not a gap, it deliberately gets no
/// table.
pub fn skipped_classes(schema: &SchemaDefinition) -> Vec<SkippedClass> {
    compute_skips(schema)
        .into_iter()
        .map(|(class, reason)| SkippedClass { class, reason })
        .collect()
}

/// The shared computation behind [`skipped_classes`] and [`render`]'s own
/// exclusion of out-of-scope classes — one pass so the two can't drift.
fn compute_skips(schema: &SchemaDefinition) -> BTreeMap<String, String> {
    let mut skips = BTreeMap::new();
    for (name, class) in &schema.classes {
        if class.r#abstract {
            continue;
        }
        if class.is_a.is_some() {
            skips.insert(
                name.clone(),
                "uses `is_a`, which this writer does not yet support".to_string(),
            );
            continue;
        }
        let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
        if let Some((slot_name, _)) = effective.iter().find(|(_, s)| s.multivalued) {
            skips.insert(
                name.clone(),
                format!(
                    "has multivalued slot `{slot_name}`, which this writer does not yet support"
                ),
            );
            continue;
        }
        if let Some((slot_name, _)) = effective.iter().find(|(_, s)| !s.any_of.is_empty()) {
            skips.insert(
                name.clone(),
                format!(
                    "has polymorphic `any_of` slot `{slot_name}`, which this writer does not yet support"
                ),
            );
        }
    }

    // Second pass: a class-range slot targeting an abstract or
    // already-skipped class would emit a foreign key to a table that's
    // never created — skip the referencing class too, rather than emit
    // broken DDL. Single pass (not a fixed point): a chain of skips more
    // than one hop deep is an edge case this writer doesn't chase.
    let is_includable = |name: &str| {
        schema.classes.get(name).is_some_and(|c| !c.r#abstract) && !skips.contains_key(name)
    };
    let mut cascaded = Vec::new();
    for (name, class) in &schema.classes {
        if class.r#abstract || skips.contains_key(name) {
            continue;
        }
        let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
        for (slot_name, slot) in &effective {
            if let Some(range) = &slot.range
                && schema.classes.contains_key(range)
                && !is_includable(range)
            {
                cascaded.push((
                    name.clone(),
                    format!(
                        "references class `{range}` (via slot `{slot_name}`), which is unsupported or itself skipped"
                    ),
                ));
                break;
            }
        }
    }
    skips.extend(cascaded);

    skips
}

/// The primary-key column name and SQL type for a class: its effective
/// `identifier` slot if one exists, else the synthesized `id uuid` key
/// every table falls back to.
fn class_primary_key(class: &ClassDefinition, schema: &SchemaDefinition) -> (String, String) {
    let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
    match effective.iter().find(|(_, slot)| slot.identifier) {
        Some((name, slot)) => {
            let col = crate::rust_writer::snake_case(name);
            let sql_type = sql_type_for_slot_range(slot.range.as_deref(), schema);
            (col, sql_type)
        }
        None => ("id".to_string(), "uuid".to_string()),
    }
}

/// Every enum referenced by an effective slot of any class, in name-sorted
/// (deterministic) order — the set of `CREATE TYPE`s to emit before any
/// table that references one.
fn referenced_enums(schema: &SchemaDefinition) -> Vec<&str> {
    let mut names = std::collections::BTreeSet::new();
    for class in schema.classes.values() {
        let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
        for slot in effective.values() {
            if let Some(range) = &slot.range
                && let Some((enum_name, _)) = schema.enums.get_key_value(range)
            {
                names.insert(enum_name.as_str());
            }
        }
    }
    names.into_iter().collect()
}

/// The Postgres column type for a slot's range: an enum type name if the
/// range resolves to a declared enum, else the scalar type mapping.
fn sql_type_for_slot_range(range: Option<&str>, schema: &SchemaDefinition) -> String {
    let range = range.unwrap_or("string");
    if schema.enums.contains_key(range) {
        crate::rust_writer::snake_case(range)
    } else {
        sql_type_for_range(range).to_string()
    }
}

/// Map a LinkML scalar range to its Postgres column type. Mirrors
/// `rust_writer::type_for_range`'s alias set for the primitive ranges.
///
/// `string`/`str`/`uri`/`uriorcurie`/`curie`/`ncname`/`objectidentifier`/
/// `nodeidentifier` all resolve to `"text"` — the same value the `_`
/// fallback below produces for any other unrecognized name — so they're
/// covered by the fallback rather than listed as their own match arm.
fn sql_type_for_range(range: &str) -> &'static str {
    match range {
        "integer" | "int" => "integer",
        "boolean" | "bool" => "boolean",
        "float" | "double" | "decimal" => "double precision",
        "date" => "date",
        "datetime" => "timestamptz",
        "time" => "time",
        _ => "text",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::linkml::{ClassDefinition, SlotDefinition};

    fn schema_with_class(class: ClassDefinition) -> SchemaDefinition {
        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert(class.name.clone(), class);
        schema
    }

    /// Parses `sql` through `pg_query` — a binding to Postgres's own C
    /// parser (`libpg_query`) — and panics with the real parse error if
    /// it isn't valid Postgres syntax. A real-Postgres-grammar oracle,
    /// not a second copy of this module's own assumptions. Every test
    /// that asserts on rendered DDL calls this too.
    fn assert_valid_postgres_sql(sql: &str) {
        if let Err(e) = pg_query::parse(sql) {
            panic!("generated DDL is not valid Postgres SQL: {e}\n\nSQL:\n{sql}");
        }
    }

    #[test]
    fn postgres_writer_format_id_is_postgres() {
        assert_eq!(PostgresWriter::new().format_id(), "postgres");
    }

    #[test]
    fn needs_parent_dir_true_for_a_nested_path() {
        assert!(needs_parent_dir(Path::new("out/schema.sql")));
    }

    #[test]
    fn needs_parent_dir_false_for_a_bare_filename() {
        // A bare filename's `.parent()` is `Some("")`, not `None` — the
        // check has to test emptiness, not just `.is_some()`.
        assert!(!needs_parent_dir(Path::new("schema.sql")));
    }

    #[test]
    fn write_creates_a_nonexistent_parent_directory_and_writes_the_file() {
        let schema = schema_with_class(ClassDefinition::new("Offering"));
        let dir = tempfile::tempdir().unwrap();
        let output = dir.path().join("nested/subdir/schema.sql");

        Writer::write(&PostgresWriter::new(), &schema, &output).unwrap();

        let written = std::fs::read_to_string(&output).unwrap();
        assert_eq!(written, PostgresWriter::new().render(&schema));
    }

    #[test]
    fn emits_create_table_with_scalar_columns() {
        let mut class = ClassDefinition::new("Offering");
        let mut name_slot = SlotDefinition::new("name");
        name_slot.range = Some("string".to_string());
        name_slot.required = true;
        class.attributes.insert("name".to_string(), name_slot);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("CREATE TABLE offering ("),
            "expected a CREATE TABLE for the class; got:\n{out}"
        );
        assert!(
            out.contains("name text NOT NULL"),
            "expected a NOT NULL text column for the required string slot; got:\n{out}"
        );
    }

    #[test]
    fn optional_scalar_slot_has_no_not_null() {
        let mut class = ClassDefinition::new("Offering");
        let mut desc_slot = SlotDefinition::new("description");
        desc_slot.range = Some("string".to_string());
        desc_slot.required = false;
        class
            .attributes
            .insert("description".to_string(), desc_slot);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("description text") && !out.contains("description text NOT NULL"),
            "an optional slot must not be NOT NULL; got:\n{out}"
        );
    }

    #[test]
    fn each_scalar_range_maps_to_a_distinct_postgres_type() {
        let mut class = ClassDefinition::new("Reading");
        for (slot_name, range) in [
            ("count", "integer"),
            ("active", "boolean"),
            ("ratio", "float"),
            ("recorded_on", "date"),
            ("recorded_at_time", "time"),
        ] {
            let mut slot = SlotDefinition::new(slot_name);
            slot.range = Some(range.to_string());
            class.attributes.insert(slot_name.to_string(), slot);
        }
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        for (slot_name, sql_type) in [
            ("count", "integer"),
            ("active", "boolean"),
            ("ratio", "double precision"),
            ("recorded_on", "date"),
            ("recorded_at_time", "time"),
        ] {
            assert!(
                out.contains(&format!("{slot_name} {sql_type}")),
                "expected `{slot_name}` typed as `{sql_type}`; got:\n{out}"
            );
        }
    }

    #[test]
    fn synthesizes_uuid_primary_key_when_no_identifier_slot() {
        let class = ClassDefinition::new("Offering");
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("id uuid PRIMARY KEY DEFAULT gen_random_uuid()"),
            "expected a synthesized uuid primary key; got:\n{out}"
        );
    }

    #[test]
    fn identifier_slot_becomes_the_primary_key() {
        let mut class = ClassDefinition::new("Offering");
        let mut sku = SlotDefinition::new("sku");
        sku.range = Some("string".to_string());
        sku.identifier = true;
        class.attributes.insert("sku".to_string(), sku);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("sku text PRIMARY KEY"),
            "expected the identifier slot to become the primary key; got:\n{out}"
        );
        assert!(
            !out.contains("id uuid PRIMARY KEY"),
            "must not also synthesize a uuid primary key; got:\n{out}"
        );
    }

    #[test]
    fn enum_range_emits_create_type_before_the_table_and_a_typed_column() {
        use crate::linkml::{EnumDefinition, PermissibleValue};
        let mut schema = SchemaDefinition::new("s");
        let mut status_enum = EnumDefinition::new("DeploymentStatus");
        status_enum
            .permissible_values
            .insert("actual".to_string(), PermissibleValue::new("actual"));
        status_enum
            .permissible_values
            .insert("planned".to_string(), PermissibleValue::new("planned"));
        schema
            .enums
            .insert("DeploymentStatus".to_string(), status_enum);

        let mut class = ClassDefinition::new("Deployment");
        let mut status_slot = SlotDefinition::new("status");
        status_slot.range = Some("DeploymentStatus".to_string());
        status_slot.required = true;
        class.attributes.insert("status".to_string(), status_slot);
        schema.classes.insert("Deployment".to_string(), class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        let create_type_pos = out
            .find("CREATE TYPE deployment_status AS ENUM ('actual', 'planned')")
            .unwrap_or_else(|| panic!("expected the enum type; got:\n{out}"));
        let create_table_pos = out
            .find("CREATE TABLE deployment (")
            .unwrap_or_else(|| panic!("expected the table; got:\n{out}"));
        assert!(
            create_type_pos < create_table_pos,
            "CREATE TYPE must precede the table that references it; got:\n{out}"
        );
        assert!(
            out.contains("status deployment_status NOT NULL"),
            "expected the column typed as the enum; got:\n{out}"
        );
    }

    #[test]
    fn single_valued_class_range_becomes_a_deferred_foreign_key() {
        let mut schema = SchemaDefinition::new("s");
        schema
            .classes
            .insert("Provider".to_string(), ClassDefinition::new("Provider"));

        let mut deployment = ClassDefinition::new("Deployment");
        let mut on_provider = SlotDefinition::new("on_provider");
        on_provider.range = Some("Provider".to_string());
        on_provider.required = false;
        deployment
            .attributes
            .insert("on_provider".to_string(), on_provider);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        // The column itself: nullable (not required), typed to match the
        // referenced table's primary key (a synthesized uuid here).
        assert!(
            out.contains("on_provider_id uuid") && !out.contains("on_provider_id uuid NOT NULL"),
            "expected a nullable FK column typed as uuid; got:\n{out}"
        );
        // The constraint is deferred (added after every CREATE TABLE) so
        // declaration order — and cycles between classes — never matter.
        let last_create_table = out.rfind("CREATE TABLE").expect("a CREATE TABLE");
        let fk_pos = out
            .find("ALTER TABLE deployment ADD CONSTRAINT deployment_on_provider_fkey FOREIGN KEY (on_provider_id) REFERENCES provider (id)")
            .unwrap_or_else(|| panic!("expected the deferred FK constraint; got:\n{out}"));
        assert!(
            fk_pos > last_create_table,
            "the FK constraint must come after every CREATE TABLE; got:\n{out}"
        );
    }

    #[test]
    fn required_single_valued_class_range_fk_column_is_not_null() {
        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert(
            "Application".to_string(),
            ClassDefinition::new("Application"),
        );

        let mut deployment = ClassDefinition::new("Deployment");
        let mut deployment_of = SlotDefinition::new("deployment_of");
        deployment_of.range = Some("Application".to_string());
        deployment_of.required = true;
        deployment
            .attributes
            .insert("deployment_of".to_string(), deployment_of);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("deployment_of_id uuid NOT NULL"),
            "a required class-range slot's FK column must be NOT NULL; got:\n{out}"
        );
    }

    #[test]
    fn fk_column_matches_a_non_synthetic_target_primary_key_type() {
        // Provider's primary key is its own `identifier` slot (text, named
        // `code`), not a synthesized uuid — the FK column must match that
        // type, and (matching LinkML's own relmodel_transformer
        // convention) must be named after the target's *actual* primary
        // key column, not a hardcoded `_id` suffix that wouldn't even
        // refer to a real column here.
        let mut schema = SchemaDefinition::new("s");
        let mut provider = ClassDefinition::new("Provider");
        let mut code = SlotDefinition::new("code");
        code.range = Some("string".to_string());
        code.identifier = true;
        provider.attributes.insert("code".to_string(), code);
        schema.classes.insert("Provider".to_string(), provider);

        let mut deployment = ClassDefinition::new("Deployment");
        let mut on_provider = SlotDefinition::new("on_provider");
        on_provider.range = Some("Provider".to_string());
        deployment
            .attributes
            .insert("on_provider".to_string(), on_provider);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("on_provider_code text"),
            "FK column must be named after the target's actual primary key column (`code`), not a hardcoded `_id`; got:\n{out}"
        );
        assert!(
            !out.contains("on_provider_id"),
            "must not also emit the old hardcoded `_id` suffix; got:\n{out}"
        );
        assert!(
            out.contains("REFERENCES provider (code)"),
            "FK must reference the target's actual primary key column; got:\n{out}"
        );
    }

    #[test]
    fn abstract_class_emits_no_table() {
        let mut class = ClassDefinition::new("InfraComponent");
        class.r#abstract = true;
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE infra_component"),
            "an abstract class must not get a table; got:\n{out}"
        );
    }

    #[test]
    fn mixin_attributes_are_flattened_into_the_mixing_class() {
        let mut auditable = ClassDefinition::new("Auditable");
        let mut created_at = SlotDefinition::new("created_at");
        created_at.range = Some("datetime".to_string());
        auditable
            .attributes
            .insert("created_at".to_string(), created_at);

        let mut deployment = ClassDefinition::new("Deployment");
        deployment.mixins = vec!["Auditable".to_string()];
        let mut status = SlotDefinition::new("status");
        status.range = Some("string".to_string());
        deployment.attributes.insert("status".to_string(), status);

        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert("Auditable".to_string(), auditable);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        let deployment_table = &out[out.find("CREATE TABLE deployment (").unwrap()..];
        assert!(
            deployment_table.contains("created_at timestamptz")
                && deployment_table.contains("status text"),
            "expected the mixin's attribute flattened alongside the class's own; got:\n{out}"
        );
        // The mixin, not being abstract, still gets its own table too.
        assert!(
            out.contains("CREATE TABLE auditable ("),
            "a non-abstract mixin still gets its own table; got:\n{out}"
        );
    }

    #[test]
    fn class_using_is_a_is_skipped_with_a_diagnostic() {
        let mut base = ClassDefinition::new("Base");
        base.r#abstract = true;
        let mut sub = ClassDefinition::new("Sub");
        sub.is_a = Some("Base".to_string());
        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert("Base".to_string(), base);
        schema.classes.insert("Sub".to_string(), sub);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE sub"),
            "a class using is_a must not get a table yet; got:\n{out}"
        );
        let skipped = skipped_classes(&schema);
        assert_eq!(
            skipped,
            vec![SkippedClass {
                class: "Sub".to_string(),
                reason: "uses `is_a`, which this writer does not yet support".to_string(),
            }]
        );
    }

    #[test]
    fn class_with_multivalued_slot_is_skipped_with_a_diagnostic() {
        let mut class = ClassDefinition::new("Deployment");
        let mut tags = SlotDefinition::new("tags");
        tags.range = Some("string".to_string());
        tags.multivalued = true;
        class.attributes.insert("tags".to_string(), tags);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE deployment"),
            "a class with a multivalued slot must not get a table yet; got:\n{out}"
        );
        assert_eq!(
            skipped_classes(&schema),
            vec![SkippedClass {
                class: "Deployment".to_string(),
                reason: "has multivalued slot `tags`, which this writer does not yet support"
                    .to_string(),
            }]
        );
    }

    #[test]
    fn class_with_any_of_slot_is_skipped_with_a_diagnostic() {
        let mut class = ClassDefinition::new("Input");
        let mut value = SlotDefinition::new("value");
        value.any_of = vec![SlotDefinition::new("a"), SlotDefinition::new("b")];
        class.attributes.insert("value".to_string(), value);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE input"),
            "a class with an any_of slot must not get a table; got:\n{out}"
        );
        assert_eq!(
            skipped_classes(&schema),
            vec![SkippedClass {
                class: "Input".to_string(),
                reason:
                    "has polymorphic `any_of` slot `value`, which this writer does not yet support"
                        .to_string(),
            }]
        );
    }

    #[test]
    fn class_referencing_a_skipped_class_is_also_skipped() {
        let mut broken = ClassDefinition::new("Broken");
        broken.is_a = Some("Base".to_string());
        let mut base = ClassDefinition::new("Base");
        base.r#abstract = true;

        let mut deployment = ClassDefinition::new("Deployment");
        let mut broken_ref = SlotDefinition::new("broken_ref");
        broken_ref.range = Some("Broken".to_string());
        deployment
            .attributes
            .insert("broken_ref".to_string(), broken_ref);

        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert("Base".to_string(), base);
        schema.classes.insert("Broken".to_string(), broken);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE deployment"),
            "a class referencing a skipped class must itself be skipped, not emit a broken FK; got:\n{out}"
        );
        let skipped = skipped_classes(&schema);
        assert!(
            skipped
                .iter()
                .any(|s| s.class == "Deployment" && s.reason.contains("Broken")),
            "expected Deployment skipped for referencing Broken; got: {skipped:?}"
        );
    }

    #[test]
    fn abstract_class_referencing_a_skipped_class_is_not_reported() {
        // Abstract classes are deliberately excluded from `skipped_classes`
        // (they get no table on purpose, which isn't a gap) — that must
        // hold even when the abstract class's own slot references another
        // class that IS a real gap (here, `Broken` uses `is_a`).
        let mut broken = ClassDefinition::new("Broken");
        broken.is_a = Some("Base".to_string());

        let mut abstract_class = ClassDefinition::new("AbstractThing");
        abstract_class.r#abstract = true;
        let mut broken_ref = SlotDefinition::new("broken_ref");
        broken_ref.range = Some("Broken".to_string());
        abstract_class
            .attributes
            .insert("broken_ref".to_string(), broken_ref);

        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert("Broken".to_string(), broken);
        schema
            .classes
            .insert("AbstractThing".to_string(), abstract_class);

        let skipped = skipped_classes(&schema);
        assert!(
            !skipped.iter().any(|s| s.class == "AbstractThing"),
            "an abstract class must never appear in skipped_classes, even if its own slot references a real gap; got: {skipped:?}"
        );
        assert!(
            skipped.iter().any(|s| s.class == "Broken"),
            "Broken must still be reported for its own is_a usage; got: {skipped:?}"
        );
    }

    /// A representative multi-class fixture combining every construct this
    /// writer supports together — an enum, a synthesized uuid PK, an
    /// identifier-derived PK, and an FK between them.
    fn whole_script_fixture_schema() -> SchemaDefinition {
        use crate::linkml::{EnumDefinition, PermissibleValue};
        let mut schema = SchemaDefinition::new("nimbus");

        let mut status_enum = EnumDefinition::new("DeploymentStatus");
        status_enum
            .permissible_values
            .insert("actual".to_string(), PermissibleValue::new("actual"));
        status_enum
            .permissible_values
            .insert("planned".to_string(), PermissibleValue::new("planned"));
        schema
            .enums
            .insert("DeploymentStatus".to_string(), status_enum);

        // Provider: identifier-derived (non-synthetic) primary key.
        let mut provider = ClassDefinition::new("Provider");
        let mut code = SlotDefinition::new("code");
        code.range = Some("string".to_string());
        code.identifier = true;
        provider.attributes.insert("code".to_string(), code);
        schema.classes.insert("Provider".to_string(), provider);

        // Deployment: synthesized uuid primary key, an enum column, and
        // an FK to Provider's identifier-derived key.
        let mut deployment = ClassDefinition::new("Deployment");
        let mut status = SlotDefinition::new("status");
        status.range = Some("DeploymentStatus".to_string());
        status.required = true;
        deployment.attributes.insert("status".to_string(), status);
        let mut on_provider = SlotDefinition::new("on_provider");
        on_provider.range = Some("Provider".to_string());
        deployment
            .attributes
            .insert("on_provider".to_string(), on_provider);
        schema.classes.insert("Deployment".to_string(), deployment);

        schema
    }

    #[test]
    fn whole_script_with_enum_fk_and_both_pk_kinds_parses_as_one_unit() {
        // Parsed as one whole script (not per-statement), so a
        // statement-ordering mistake (e.g. a CREATE TYPE after the table
        // that needs it) would fail this even if each statement parsed
        // individually.
        let schema = whole_script_fixture_schema();

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        // Sanity that this fixture actually exercises what it claims to
        // (a failure here means the test stopped covering what its name
        // says, independent of whether pg_query accepts the output).
        assert!(out.contains("CREATE TYPE deployment_status AS ENUM"));
        assert!(out.contains("code text PRIMARY KEY"));
        assert!(out.contains("id uuid PRIMARY KEY DEFAULT gen_random_uuid()"));
        assert!(out.contains("ALTER TABLE deployment ADD CONSTRAINT"));
    }

    #[test]
    fn unique_keys_emit_a_table_level_unique_constraint() {
        use crate::linkml::UniqueKey;
        let mut class = ClassDefinition::new("Offering");
        let mut service_type = SlotDefinition::new("service_type");
        service_type.range = Some("string".to_string());
        class
            .attributes
            .insert("service_type".to_string(), service_type);
        let mut offered_by = SlotDefinition::new("offered_by");
        offered_by.range = Some("string".to_string());
        class
            .attributes
            .insert("offered_by".to_string(), offered_by);
        class.unique_keys.insert(
            "service_offering".to_string(),
            UniqueKey {
                unique_key_slots: vec!["service_type".to_string(), "offered_by".to_string()],
                description: None,
            },
        );
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains(
                "CONSTRAINT offering_service_offering_key UNIQUE (service_type, offered_by)"
            ),
            "expected a named table-level UNIQUE constraint over the key's slot tuple; got:\n{out}"
        );
    }

    #[test]
    fn pattern_emits_an_inline_check_constraint() {
        let mut class = ClassDefinition::new("Provider");
        let mut code = SlotDefinition::new("code");
        code.range = Some("string".to_string());
        code.pattern = Some("^[A-Z]{3}$".to_string());
        class.attributes.insert("code".to_string(), code);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("code text CHECK (code ~ '^[A-Z]{3}$')"),
            "expected an inline regex CHECK on the patterned column; got:\n{out}"
        );
    }

    #[test]
    fn pattern_single_quotes_are_escaped() {
        // A pattern containing a single quote must be doubled (`''`), or the
        // generated CHECK is a syntax error / injection. pg_query catches
        // it if we get this wrong.
        let mut class = ClassDefinition::new("Note");
        let mut body = SlotDefinition::new("body");
        body.range = Some("string".to_string());
        body.pattern = Some("it's".to_string());
        class.attributes.insert("body".to_string(), body);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("CHECK (body ~ 'it''s')"),
            "single quotes in a pattern must be doubled; got:\n{out}"
        );
    }

    #[test]
    fn both_value_bounds_emit_one_combined_check() {
        let mut class = ClassDefinition::new("Reading");
        let mut level = SlotDefinition::new("level");
        level.range = Some("integer".to_string());
        level.minimum_value = Some(0.0);
        level.maximum_value = Some(100.0);
        class.attributes.insert("level".to_string(), level);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("level integer CHECK (level >= 0 AND level <= 100)"),
            "both bounds must combine into one CHECK; got:\n{out}"
        );
    }

    #[test]
    fn a_single_value_bound_emits_only_that_side() {
        let mut class = ClassDefinition::new("Reading");
        let mut ratio = SlotDefinition::new("ratio");
        ratio.range = Some("float".to_string());
        ratio.minimum_value = Some(0.0);
        class.attributes.insert("ratio".to_string(), ratio);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("ratio double precision CHECK (ratio >= 0)"),
            "a lone minimum_value must emit only the `>=` side; got:\n{out}"
        );
        assert!(
            !out.contains("<="),
            "no maximum_value set, so no `<=` clause; got:\n{out}"
        );
    }

    #[test]
    fn a_lone_maximum_value_emits_only_the_upper_bound() {
        let mut class = ClassDefinition::new("Reading");
        let mut ratio = SlotDefinition::new("ratio");
        ratio.range = Some("float".to_string());
        ratio.maximum_value = Some(1.0);
        class.attributes.insert("ratio".to_string(), ratio);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("ratio double precision CHECK (ratio <= 1)"),
            "a lone maximum_value must emit only the `<=` side; got:\n{out}"
        );
        assert!(
            !out.contains(">="),
            "no minimum_value set, so no `>=` clause; got:\n{out}"
        );
    }

    #[test]
    fn unique_key_naming_a_missing_slot_is_dropped_not_emitted() {
        // A key referencing a slot the class doesn't have must not emit a
        // UNIQUE clause naming a nonexistent column (which would be broken
        // DDL). The CLI separately warns about it via
        // `diagnostics::unresolved_unique_key_slots`; the writer itself
        // must still never emit broken SQL even if that warning is ignored.
        use crate::linkml::UniqueKey;
        let mut class = ClassDefinition::new("Offering");
        let mut service_type = SlotDefinition::new("service_type");
        service_type.range = Some("string".to_string());
        class
            .attributes
            .insert("service_type".to_string(), service_type);
        class.unique_keys.insert(
            "bad_key".to_string(),
            UniqueKey {
                unique_key_slots: vec!["service_type".to_string(), "ghost".to_string()],
                description: None,
            },
        );
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("ghost"),
            "a key naming a slot the class lacks must not appear in the DDL; got:\n{out}"
        );
        assert!(
            !out.contains("bad_key"),
            "a key with an unresolved slot must be dropped entirely, not emitted partially; got:\n{out}"
        );
    }

    #[test]
    #[ignore = "needs Docker; run with `cargo nextest run -p panschema --features dev --run-ignored=only -E 'test(postgres_apply)'`"]
    fn postgres_apply_applies_generated_ddl_to_a_real_database() {
        // pg_query (above) proves the DDL is syntactically valid Postgres;
        // it can't catch a semantic error like an FK column whose type
        // doesn't match its target's real primary key. Applying the DDL
        // against a real, disposable Postgres container is the oracle
        // that would.
        use testcontainers_modules::postgres::Postgres;
        use testcontainers_modules::testcontainers::ImageExt;
        use testcontainers_modules::testcontainers::runners::SyncRunner;

        let ddl = PostgresWriter::new().render(&whole_script_fixture_schema());

        // Pinned rather than the module's own default (Postgres 11):
        // `gen_random_uuid()` — used for every synthesized primary key —
        // is only built into Postgres 13+, so testing against an older
        // default would fail on this writer's own generated DDL.
        let node = Postgres::default()
            .with_tag("16-alpine")
            .start()
            .expect("failed to start Postgres container");
        let port = node
            .get_host_port_ipv4(5432)
            .expect("failed to get container's mapped port");
        let connection_string = format!("postgres://postgres:postgres@127.0.0.1:{port}/postgres");
        let mut client = postgres::Client::connect(&connection_string, postgres::NoTls)
            .expect("failed to connect to Postgres container");

        client.batch_execute(&ddl).unwrap_or_else(|e| {
            panic!("generated DDL failed to apply to a real Postgres database: {e}\n\nDDL:\n{ddl}")
        });
    }
}
