//! Postgres DDL writer
//!
//! Writes the LinkML IR to Postgres `CREATE TABLE` DDL: concrete classes,
//! scalar attributes, enums, and single-valued class references. See
//! `docs/features/24-postgres-ddl-writer.md` for the full design,
//! including constructs not yet covered here.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use crate::io::{IoError, IoResult, Writer};
use crate::linkml::{ClassDefinition, SchemaDefinition};

/// Writer for Postgres DDL (`CREATE TABLE` / `CREATE TYPE`).
pub struct PostgresWriter;

impl PostgresWriter {
    pub fn new() -> Self {
        Self
    }

    /// Render the schema to a complete DDL script.
    pub fn render(&self, schema: &SchemaDefinition) -> String {
        render(schema)
    }
}

impl Default for PostgresWriter {
    fn default() -> Self {
        Self::new()
    }
}

impl Writer for PostgresWriter {
    fn write(&self, schema: &SchemaDefinition, output: &Path) -> IoResult<()> {
        crate::io::ensure_output_parent(output)?;
        std::fs::write(output, self.render(schema)).map_err(IoError::Io)?;
        Ok(())
    }

    fn format_id(&self) -> &str {
        "postgres"
    }
}

/// Double-quote a Postgres identifier, doubling any embedded `"`. Applied
/// to every identifier this writer interpolates into SQL — table, column,
/// enum type, and constraint names. Quoting is unconditional: it makes
/// reserved words (a class named `Order`) legal, and it confines a
/// hostile or merely unusual name to the identifier position instead of
/// letting it alter the statement. Names are snake_cased (lowercased)
/// first, so quoting doesn't change how well-formed names resolve.
fn quote_ident(name: &str) -> String {
    format!("\"{}\"", name.replace('"', "\"\""))
}

fn render(schema: &SchemaDefinition) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "-- @generated by panschema v{}",
        env!("CARGO_PKG_VERSION")
    )
    .ok();
    writeln!(out, "-- Schema: {}", schema.name).ok();
    writeln!(out).ok();

    for enum_name in referenced_enums(schema) {
        let def = &schema.enums[enum_name];
        let type_name = crate::casing::snake_case(enum_name);
        let values: Vec<String> = def
            .permissible_values
            .keys()
            .map(|v| format!("'{}'", v.replace('\'', "''")))
            .collect();
        writeln!(
            out,
            "CREATE TYPE {} AS ENUM ({});",
            quote_ident(&type_name),
            values.join(", ")
        )
        .ok();
    }
    writeln!(out).ok();

    // Foreign-key constraints are deferred: added via `ALTER TABLE` after
    // every `CREATE TABLE`, so declaration order (and cycles between
    // classes) never matter — the script still applies in one pass.
    let mut fk_constraints = Vec::new();
    let skips = compute_skips(schema);

    for (class_name, class) in &schema.classes {
        if class.r#abstract {
            // Not meant to be instantiated — nothing to hold a row.
            continue;
        }
        if skips.contains_key(class_name) {
            // Not yet supported (is_a / multivalued / any_of / references
            // a skipped class) — see `skipped_classes` for the diagnostic
            // surfaced to the caller.
            continue;
        }
        let table = crate::casing::snake_case(class_name);
        let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
        let (pk_col, pk_type) = class_primary_key(class, schema);

        // The identifier-marked slot (if any) becomes the primary key
        // column instead of a synthetic one.
        let pk_slot = effective
            .iter()
            .find(|(_, slot)| slot.identifier)
            .map(|(name, _)| name.clone());

        writeln!(out, "CREATE TABLE {} (", quote_ident(&table)).ok();
        let mut lines = vec![format!(
            "    {} {pk_type} PRIMARY KEY{}",
            quote_ident(&pk_col),
            if pk_slot.is_none() {
                " DEFAULT gen_random_uuid()"
            } else {
                ""
            }
        )];
        // Slot name → the column name it actually resolves to, so the
        // table-level constraints below (`unique_keys`, `rules`) can name
        // the real columns. The single source of column naming, shared with
        // `skipped_rules` so its skip decision can't drift from what `render`
        // actually emits.
        let slot_columns = slot_column_map(class, schema);
        for (slot_name, slot) in &effective {
            if pk_slot.as_deref() == Some(slot_name.as_str()) {
                continue;
            }
            let col = &slot_columns[slot_name];
            // NOT NULL follows the *effective* lower bound: an explicit
            // `minimum_cardinality >= 1` makes a column required even without
            // the `required` flag, the same reconciliation HTML and SHACL use.
            let not_null = if crate::linkml_resolve::effective_cardinality(slot).required {
                " NOT NULL"
            } else {
                ""
            };
            let range = slot.range.as_deref();
            if let Some(target_class) = range.and_then(|r| schema.classes.get_key_value(r)) {
                let (target_name, target_def) = target_class;
                let (target_pk_col, target_pk_type) = class_primary_key(target_def, schema);
                lines.push(format!(
                    "    {} {target_pk_type}{not_null}",
                    quote_ident(col)
                ));
                fk_constraints.push(FkConstraint {
                    from_table: table.clone(),
                    from_col: col.clone(),
                    to_table: crate::casing::snake_case(target_name),
                    to_col: target_pk_col,
                    constraint_name: format!(
                        "{table}_{}_fkey",
                        crate::casing::snake_case(slot_name)
                    ),
                });
            } else {
                let sql_type = sql_type_for_slot_range(range, schema);
                let checks = column_checks(col, slot);
                lines.push(format!(
                    "    {} {sql_type}{not_null}{checks}",
                    quote_ident(col)
                ));
            }
        }
        // Table-level UNIQUE constraints from `unique_keys`. A key that
        // names a slot the class doesn't have is dropped entirely rather
        // than emitting a UNIQUE over a nonexistent column — the same
        // gap `diagnostics::unresolved_unique_key_slots` warns about on
        // the CLI path, enforced here so the writer never emits broken
        // DDL even if that warning is ignored.
        for (key_name, key) in &class.unique_keys {
            let cols: Option<Vec<&String>> = key
                .unique_key_slots
                .iter()
                .map(|s| slot_columns.get(s.as_str()))
                .collect();
            if let Some(cols) = cols {
                let col_list = cols
                    .iter()
                    .map(|c| quote_ident(c))
                    .collect::<Vec<_>>()
                    .join(", ");
                lines.push(format!(
                    "    CONSTRAINT {} UNIQUE ({col_list})",
                    quote_ident(&format!(
                        "{table}_{}_key",
                        crate::casing::snake_case(key_name)
                    ))
                ));
            }
        }
        // Conditional `CHECK` constraints from `rules`: `NOT (pre) OR (post)`,
        // the standard SQL encoding of "when precondition holds, postcondition
        // must too". A rule that can't be expressed as a column CHECK is
        // dropped here (and separately surfaced by `skipped_rules` on the CLI
        // path) rather than emitted broken.
        for (i, rule) in class.rules.iter().enumerate() {
            if let (Some(pre), Some(post)) = (&rule.preconditions, &rule.postconditions)
                && let (Some(p_sql), Some(q_sql)) = (
                    rule_conditions_to_sql(pre, &slot_columns),
                    rule_conditions_to_sql(post, &slot_columns),
                )
            {
                lines.push(format!(
                    "    CONSTRAINT {} CHECK (NOT ({p_sql}) OR ({q_sql}))",
                    quote_ident(&format!("{table}_rule{i}_check"))
                ));
            }
        }
        writeln!(out, "{}", lines.join(",\n")).ok();
        writeln!(out, ");").ok();
        writeln!(out).ok();
    }

    for fk in &fk_constraints {
        writeln!(
            out,
            "ALTER TABLE {} ADD CONSTRAINT {} FOREIGN KEY ({}) REFERENCES {} ({});",
            quote_ident(&fk.from_table),
            quote_ident(&fk.constraint_name),
            quote_ident(&fk.from_col),
            quote_ident(&fk.to_table),
            quote_ident(&fk.to_col)
        )
        .ok();
    }

    out
}

/// Inline `CHECK` clauses for a scalar column, from the slot's value
/// constraints — the leading-space-prefixed suffix appended to the column
/// definition. Empty when the slot has none.
///
/// - `pattern` → `CHECK (col ~ 'regex')` (single quotes doubled so the
///   literal can't break the statement, same escaping the enum values use).
/// - `minimum_value` / `maximum_value` → a single `CHECK` combining both
///   with `AND` when both are set, or just the one side when only one is.
fn column_checks(col: &str, slot: &crate::linkml::SlotDefinition) -> String {
    let col = quote_ident(col);
    let mut checks = String::new();
    if let Some(p) = &slot.pattern {
        checks.push_str(&format!(" CHECK ({col} ~ '{}')", p.replace('\'', "''")));
    }
    let bound = match (slot.minimum_value, slot.maximum_value) {
        (Some(min), Some(max)) => Some(format!("{col} >= {min} AND {col} <= {max}")),
        (Some(min), None) => Some(format!("{col} >= {min}")),
        (None, Some(max)) => Some(format!("{col} <= {max}")),
        (None, None) => None,
    };
    if let Some(b) = bound {
        checks.push_str(&format!(" CHECK ({b})"));
    }
    checks
}

/// Every effective slot of `class` mapped to the column name it becomes:
/// the identifier slot to the primary-key column, a single-valued
/// class-range slot to its `{slot}_{target_pk}` foreign-key column, and any
/// other scalar slot to its bare `snake_case` name. The one place column
/// naming is decided, so `render` (emission) and `skipped_rules`
/// (diagnostic) can't disagree about which columns exist.
fn slot_column_map(class: &ClassDefinition, schema: &SchemaDefinition) -> BTreeMap<String, String> {
    let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
    let (pk_col, _) = class_primary_key(class, schema);
    let pk_slot = effective
        .iter()
        .find(|(_, slot)| slot.identifier)
        .map(|(name, _)| name.clone());

    let mut map = BTreeMap::new();
    if let Some(pk) = &pk_slot {
        map.insert(pk.clone(), pk_col.clone());
    }
    for (slot_name, slot) in &effective {
        if pk_slot.as_deref() == Some(slot_name.as_str()) {
            continue;
        }
        let col = match slot.range.as_deref().and_then(|r| schema.classes.get(r)) {
            Some(target_def) => {
                let (target_pk_col, _) = class_primary_key(target_def, schema);
                format!("{}_{}", crate::casing::snake_case(slot_name), target_pk_col)
            }
            None => crate::casing::snake_case(slot_name),
        };
        map.insert(slot_name.clone(), col);
    }
    map
}

/// Map a rule's `slot_conditions` to a SQL boolean expression — the `AND`
/// of every condition's predicates — or `None` if the conditions can't be
/// expressed as a column `CHECK`. Unexpressible when: the map is empty; a
/// referenced slot isn't a column of this class (`slot_columns` miss); a
/// condition carries a `range` or cardinality field (no single-column SQL
/// form); or a condition has no expressible field at all. The field →
/// predicate mapping mirrors the HTML "when … then …" sentence
/// (`html_writer.rs`'s `describe_slot_condition`).
fn rule_conditions_to_sql(
    conds: &crate::linkml::RuleConditions,
    slot_columns: &BTreeMap<String, String>,
) -> Option<String> {
    if conds.slot_conditions.is_empty() {
        return None;
    }
    let mut preds = Vec::new();
    for (slot, cond) in &conds.slot_conditions {
        let col = quote_ident(slot_columns.get(slot.as_str())?);
        // Fields with no single-column CHECK form make the whole rule
        // unexpressible (the HTML card can still render them).
        if cond.range.is_some()
            || cond.minimum_cardinality.is_some()
            || cond.maximum_cardinality.is_some()
        {
            return None;
        }
        if let Some(v) = &cond.equals_string {
            preds.push(format!("{col} = '{}'", v.replace('\'', "''")));
        }
        if let Some(n) = cond.equals_number {
            preds.push(format!("{col} = {n}"));
        }
        if cond.required {
            preds.push(format!("{col} IS NOT NULL"));
        }
        if let Some(p) = &cond.pattern {
            preds.push(format!("{col} ~ '{}'", p.replace('\'', "''")));
        }
        if let Some(m) = cond.minimum_value {
            preds.push(format!("{col} >= {m}"));
        }
        if let Some(m) = cond.maximum_value {
            preds.push(format!("{col} <= {m}"));
        }
    }
    if preds.is_empty() {
        return None;
    }
    Some(preds.join(" AND "))
}

/// A deferred foreign-key constraint, added after every table is declared.
struct FkConstraint {
    from_table: String,
    from_col: String,
    to_table: String,
    to_col: String,
    constraint_name: String,
}

/// A class this writer doesn't project to a table, and why.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkippedClass {
    pub class: String,
    pub reason: String,
}

/// Classes [`render`] skips, with a diagnostic naming why — `is_a`,
/// a multivalued slot, an `any_of` slot, or a class-range slot that
/// targets one of those (which would otherwise emit a foreign key to a
/// table that's never created), are all not yet supported. An abstract
/// class isn't reported here — it's not a gap, it deliberately gets no
/// table.
pub fn skipped_classes(schema: &SchemaDefinition) -> Vec<SkippedClass> {
    compute_skips(schema)
        .into_iter()
        .map(|(class, reason)| SkippedClass { class, reason })
        .collect()
}

/// A `rules` entry [`render`] can't project to a `CHECK` constraint, and why.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkippedRule {
    pub class: String,
    /// The rule's title, or `rule #<n>` (its position) when it has none.
    pub rule: String,
    pub reason: String,
}

/// Rules [`render`] can't emit as a conditional `CHECK`, with a diagnostic
/// naming each. A rule is unexpressible when it has only one of
/// pre/postconditions, or a condition side that can't become a column
/// predicate (empty, a `range`/cardinality field, or a slot the class
/// doesn't have). Shares [`slot_column_map`] and [`rule_conditions_to_sql`]
/// with `render`, so this reports exactly the rules `render` drops — no
/// drift between the warning and the emitted DDL. Classes that get no table
/// at all (abstract, or skipped per [`compute_skips`]) contribute no rule
/// diagnostics — their omission is already covered by [`skipped_classes`].
pub fn skipped_rules(schema: &SchemaDefinition) -> Vec<SkippedRule> {
    let skips = compute_skips(schema);
    let mut out = Vec::new();
    for (class_name, class) in &schema.classes {
        if class.r#abstract || skips.contains_key(class_name) || class.rules.is_empty() {
            continue;
        }
        let slot_columns = slot_column_map(class, schema);
        for (i, rule) in class.rules.iter().enumerate() {
            if let Some(reason) = rule_skip_reason(rule, &slot_columns) {
                out.push(SkippedRule {
                    class: class_name.clone(),
                    rule: rule.title.clone().unwrap_or_else(|| format!("rule #{i}")),
                    reason,
                });
            }
        }
    }
    out
}

/// Why [`render`] would skip `rule`, or `None` if it emits a `CHECK`. Calls
/// the same [`rule_conditions_to_sql`] `render` uses, so the decision is
/// identical.
fn rule_skip_reason(
    rule: &crate::linkml::ClassRule,
    slot_columns: &BTreeMap<String, String>,
) -> Option<String> {
    match (&rule.preconditions, &rule.postconditions) {
        (Some(pre), Some(post)) => {
            if rule_conditions_to_sql(pre, slot_columns).is_none() {
                Some(
                    "its preconditions can't be expressed as a Postgres CHECK (empty, a `range`/cardinality condition, or a slot the class doesn't have)"
                        .to_string(),
                )
            } else if rule_conditions_to_sql(post, slot_columns).is_none() {
                Some(
                    "its postconditions can't be expressed as a Postgres CHECK (empty, a `range`/cardinality condition, or a slot the class doesn't have)"
                        .to_string(),
                )
            } else {
                None
            }
        }
        _ => Some("a Postgres CHECK needs both preconditions and postconditions".to_string()),
    }
}

/// The shared computation behind [`skipped_classes`] and [`render`]'s own
/// exclusion of out-of-scope classes — one pass so the two can't drift.
fn compute_skips(schema: &SchemaDefinition) -> BTreeMap<String, String> {
    let mut skips = BTreeMap::new();
    for (name, class) in &schema.classes {
        if class.r#abstract {
            continue;
        }
        if class.is_a.is_some() {
            skips.insert(
                name.clone(),
                "uses `is_a`, which this writer does not yet support".to_string(),
            );
            continue;
        }
        let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
        if let Some((slot_name, _)) = effective.iter().find(|(_, s)| s.multivalued) {
            skips.insert(
                name.clone(),
                format!(
                    "has multivalued slot `{slot_name}`, which this writer does not yet support"
                ),
            );
            continue;
        }
        if let Some((slot_name, _)) = effective.iter().find(|(_, s)| !s.any_of.is_empty()) {
            skips.insert(
                name.clone(),
                format!(
                    "has polymorphic `any_of` slot `{slot_name}`, which this writer does not yet support"
                ),
            );
        }
    }

    // Second pass: a class-range slot targeting an abstract or
    // already-skipped class would emit a foreign key to a table that's
    // never created — skip the referencing class too, rather than emit
    // broken DDL. Single pass (not a fixed point): a chain of skips more
    // than one hop deep is an edge case this writer doesn't chase.
    let is_includable = |name: &str| {
        schema.classes.get(name).is_some_and(|c| !c.r#abstract) && !skips.contains_key(name)
    };
    let mut cascaded = Vec::new();
    for (name, class) in &schema.classes {
        if class.r#abstract || skips.contains_key(name) {
            continue;
        }
        let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
        for (slot_name, slot) in &effective {
            if let Some(range) = &slot.range
                && schema.classes.contains_key(range)
                && !is_includable(range)
            {
                cascaded.push((
                    name.clone(),
                    format!(
                        "references class `{range}` (via slot `{slot_name}`), which is unsupported or itself skipped"
                    ),
                ));
                break;
            }
        }
    }
    skips.extend(cascaded);

    skips
}

/// The primary-key column name and SQL type for a class: its effective
/// `identifier` slot if one exists, else the synthesized `id uuid` key
/// every table falls back to.
fn class_primary_key(class: &ClassDefinition, schema: &SchemaDefinition) -> (String, String) {
    let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
    match effective.iter().find(|(_, slot)| slot.identifier) {
        Some((name, slot)) => {
            let col = crate::casing::snake_case(name);
            let sql_type = sql_type_for_slot_range(slot.range.as_deref(), schema);
            (col, sql_type)
        }
        None => ("id".to_string(), "uuid".to_string()),
    }
}

/// Every enum referenced by an effective slot of any class, in name-sorted
/// (deterministic) order — the set of `CREATE TYPE`s to emit before any
/// table that references one.
fn referenced_enums(schema: &SchemaDefinition) -> Vec<&str> {
    let mut names = std::collections::BTreeSet::new();
    for class in schema.classes.values() {
        let effective = crate::linkml_resolve::resolve_effective_slots(class, schema);
        for slot in effective.values() {
            if let Some(range) = &slot.range
                && let Some((enum_name, _)) = schema.enums.get_key_value(range)
            {
                names.insert(enum_name.as_str());
            }
        }
    }
    names.into_iter().collect()
}

/// The Postgres column type for a slot's range: an enum type name (quoted —
/// it's an identifier this writer itself declares) if the range resolves to
/// a declared enum, else the scalar type mapping (a builtin type keyword,
/// never quoted).
fn sql_type_for_slot_range(range: Option<&str>, schema: &SchemaDefinition) -> String {
    let range = range.unwrap_or("string");
    if schema.enums.contains_key(range) {
        quote_ident(&crate::casing::snake_case(range))
    } else {
        sql_type_for_range(range).to_string()
    }
}

/// Map a LinkML scalar range to its Postgres column type. Mirrors
/// `rust_writer::type_for_range`'s alias set for the primitive ranges.
///
/// `string`/`str`/`uri`/`uriorcurie`/`curie`/`ncname`/`objectidentifier`/
/// `nodeidentifier` all resolve to `"text"` — the same value the `_`
/// fallback below produces for any other unrecognized name — so they're
/// covered by the fallback rather than listed as their own match arm.
fn sql_type_for_range(range: &str) -> &'static str {
    match range {
        "integer" | "int" => "integer",
        "boolean" | "bool" => "boolean",
        "float" | "double" | "decimal" => "double precision",
        "date" => "date",
        "datetime" => "timestamptz",
        "time" => "time",
        _ => "text",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::linkml::{ClassDefinition, SlotDefinition};

    fn schema_with_class(class: ClassDefinition) -> SchemaDefinition {
        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert(class.name.clone(), class);
        schema
    }

    /// Parses `sql` through `pg_query` — a binding to Postgres's own C
    /// parser (`libpg_query`) — and panics with the real parse error if
    /// it isn't valid Postgres syntax. A real-Postgres-grammar oracle,
    /// not a second copy of this module's own assumptions. Every test
    /// that asserts on rendered DDL calls this too.
    fn assert_valid_postgres_sql(sql: &str) {
        if let Err(e) = pg_query::parse(sql) {
            panic!("generated DDL is not valid Postgres SQL: {e}\n\nSQL:\n{sql}");
        }
    }

    #[test]
    fn postgres_writer_format_id_is_postgres() {
        assert_eq!(PostgresWriter::new().format_id(), "postgres");
    }

    #[test]
    fn write_creates_a_nonexistent_parent_directory_and_writes_the_file() {
        let schema = schema_with_class(ClassDefinition::new("Offering"));
        let dir = tempfile::tempdir().unwrap();
        let output = dir.path().join("nested/subdir/schema.sql");

        Writer::write(&PostgresWriter::new(), &schema, &output).unwrap();

        let written = std::fs::read_to_string(&output).unwrap();
        assert_eq!(written, PostgresWriter::new().render(&schema));
    }

    #[test]
    fn reserved_word_class_name_emits_quoted_applicable_ddl() {
        // `ORDER` is a fully reserved Postgres keyword: unquoted
        // `CREATE TABLE order (...)` is a syntax error the pg_query oracle
        // rejects. Quoting every identifier makes the name legal.
        let mut class = ClassDefinition::new("Order");
        let mut placed_at = SlotDefinition::new("placed_at");
        placed_at.range = Some("datetime".to_string());
        class.attributes.insert("placed_at".to_string(), placed_at);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("CREATE TABLE \"order\" ("),
            "reserved-word class name must emit a quoted table identifier; got:\n{out}"
        );
    }

    #[test]
    fn hostile_class_name_stays_inside_its_quoted_identifier() {
        // A name crafted to break out of the identifier position must end
        // up entirely inside one quoted identifier — the parsed script may
        // contain only CREATE statements, never a smuggled DROP.
        let mut class = ClassDefinition::new("Evil (x int); DROP TABLE users; --");
        let mut name_slot = SlotDefinition::new("name");
        name_slot.range = Some("string".to_string());
        class.attributes.insert("name".to_string(), name_slot);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        let parsed = pg_query::parse(&out).expect("already validated above");
        let tree = format!("{parsed:?}");
        assert!(
            !tree.contains("DropStmt"),
            "hostile name must not smuggle a DROP statement into the parse tree; got:\n{out}"
        );
    }

    #[test]
    fn emits_create_table_with_scalar_columns() {
        let mut class = ClassDefinition::new("Offering");
        let mut name_slot = SlotDefinition::new("name");
        name_slot.range = Some("string".to_string());
        name_slot.required = true;
        class.attributes.insert("name".to_string(), name_slot);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("CREATE TABLE \"offering\" ("),
            "expected a CREATE TABLE for the class; got:\n{out}"
        );
        assert!(
            out.contains("\"name\" text NOT NULL"),
            "expected a NOT NULL text column for the required string slot; got:\n{out}"
        );
    }

    #[test]
    fn optional_scalar_slot_has_no_not_null() {
        let mut class = ClassDefinition::new("Offering");
        let mut desc_slot = SlotDefinition::new("description");
        desc_slot.range = Some("string".to_string());
        desc_slot.required = false;
        class
            .attributes
            .insert("description".to_string(), desc_slot);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"description\" text") && !out.contains("\"description\" text NOT NULL"),
            "an optional slot must not be NOT NULL; got:\n{out}"
        );
    }

    #[test]
    fn minimum_cardinality_of_one_makes_a_column_not_null() {
        // NOT NULL must reflect *effective* cardinality, not the raw
        // `required` flag: a slot with `minimum_cardinality: 1` is required
        // even when `required` is unset, matching how HTML/SHACL read it.
        let mut class = ClassDefinition::new("Offering");
        let mut code_slot = SlotDefinition::new("code");
        code_slot.range = Some("string".to_string());
        code_slot.required = false;
        code_slot.minimum_cardinality = Some(1);
        class.attributes.insert("code".to_string(), code_slot);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"code\" text NOT NULL"),
            "minimum_cardinality >= 1 must make the column NOT NULL; got:\n{out}"
        );
    }

    #[test]
    fn each_scalar_range_maps_to_a_distinct_postgres_type() {
        let mut class = ClassDefinition::new("Reading");
        for (slot_name, range) in [
            ("count", "integer"),
            ("active", "boolean"),
            ("ratio", "float"),
            ("recorded_on", "date"),
            ("recorded_at_time", "time"),
        ] {
            let mut slot = SlotDefinition::new(slot_name);
            slot.range = Some(range.to_string());
            class.attributes.insert(slot_name.to_string(), slot);
        }
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        for (slot_name, sql_type) in [
            ("count", "integer"),
            ("active", "boolean"),
            ("ratio", "double precision"),
            ("recorded_on", "date"),
            ("recorded_at_time", "time"),
        ] {
            assert!(
                out.contains(&format!("\"{slot_name}\" {sql_type}")),
                "expected `{slot_name}` typed as `{sql_type}`; got:\n{out}"
            );
        }
    }

    #[test]
    fn synthesizes_uuid_primary_key_when_no_identifier_slot() {
        let class = ClassDefinition::new("Offering");
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid()"),
            "expected a synthesized uuid primary key; got:\n{out}"
        );
    }

    #[test]
    fn identifier_slot_becomes_the_primary_key() {
        let mut class = ClassDefinition::new("Offering");
        let mut sku = SlotDefinition::new("sku");
        sku.range = Some("string".to_string());
        sku.identifier = true;
        class.attributes.insert("sku".to_string(), sku);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"sku\" text PRIMARY KEY"),
            "expected the identifier slot to become the primary key; got:\n{out}"
        );
        assert!(
            !out.contains("\"id\" uuid PRIMARY KEY"),
            "must not also synthesize a uuid primary key; got:\n{out}"
        );
    }

    #[test]
    fn enum_range_emits_create_type_before_the_table_and_a_typed_column() {
        use crate::linkml::{EnumDefinition, PermissibleValue};
        let mut schema = SchemaDefinition::new("s");
        let mut status_enum = EnumDefinition::new("DeploymentStatus");
        status_enum
            .permissible_values
            .insert("actual".to_string(), PermissibleValue::new("actual"));
        status_enum
            .permissible_values
            .insert("planned".to_string(), PermissibleValue::new("planned"));
        schema
            .enums
            .insert("DeploymentStatus".to_string(), status_enum);

        let mut class = ClassDefinition::new("Deployment");
        let mut status_slot = SlotDefinition::new("status");
        status_slot.range = Some("DeploymentStatus".to_string());
        status_slot.required = true;
        class.attributes.insert("status".to_string(), status_slot);
        schema.classes.insert("Deployment".to_string(), class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        let create_type_pos = out
            .find("CREATE TYPE \"deployment_status\" AS ENUM ('actual', 'planned')")
            .unwrap_or_else(|| panic!("expected the enum type; got:\n{out}"));
        let create_table_pos = out
            .find("CREATE TABLE \"deployment\" (")
            .unwrap_or_else(|| panic!("expected the table; got:\n{out}"));
        assert!(
            create_type_pos < create_table_pos,
            "CREATE TYPE must precede the table that references it; got:\n{out}"
        );
        assert!(
            out.contains("\"status\" \"deployment_status\" NOT NULL"),
            "expected the column typed as the enum; got:\n{out}"
        );
    }

    #[test]
    fn single_valued_class_range_becomes_a_deferred_foreign_key() {
        let mut schema = SchemaDefinition::new("s");
        schema
            .classes
            .insert("Provider".to_string(), ClassDefinition::new("Provider"));

        let mut deployment = ClassDefinition::new("Deployment");
        let mut on_provider = SlotDefinition::new("on_provider");
        on_provider.range = Some("Provider".to_string());
        on_provider.required = false;
        deployment
            .attributes
            .insert("on_provider".to_string(), on_provider);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        // The column itself: nullable (not required), typed to match the
        // referenced table's primary key (a synthesized uuid here).
        assert!(
            out.contains("\"on_provider_id\" uuid")
                && !out.contains("\"on_provider_id\" uuid NOT NULL"),
            "expected a nullable FK column typed as uuid; got:\n{out}"
        );
        // The constraint is deferred (added after every CREATE TABLE) so
        // declaration order — and cycles between classes — never matter.
        let last_create_table = out.rfind("CREATE TABLE").expect("a CREATE TABLE");
        let fk_pos = out
            .find("ALTER TABLE \"deployment\" ADD CONSTRAINT \"deployment_on_provider_fkey\" FOREIGN KEY (\"on_provider_id\") REFERENCES \"provider\" (\"id\")")
            .unwrap_or_else(|| panic!("expected the deferred FK constraint; got:\n{out}"));
        assert!(
            fk_pos > last_create_table,
            "the FK constraint must come after every CREATE TABLE; got:\n{out}"
        );
    }

    #[test]
    fn required_single_valued_class_range_fk_column_is_not_null() {
        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert(
            "Application".to_string(),
            ClassDefinition::new("Application"),
        );

        let mut deployment = ClassDefinition::new("Deployment");
        let mut deployment_of = SlotDefinition::new("deployment_of");
        deployment_of.range = Some("Application".to_string());
        deployment_of.required = true;
        deployment
            .attributes
            .insert("deployment_of".to_string(), deployment_of);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"deployment_of_id\" uuid NOT NULL"),
            "a required class-range slot's FK column must be NOT NULL; got:\n{out}"
        );
    }

    #[test]
    fn fk_column_matches_a_non_synthetic_target_primary_key_type() {
        // Provider's primary key is its own `identifier` slot (text, named
        // `code`), not a synthesized uuid — the FK column must match that
        // type, and (matching LinkML's own relmodel_transformer
        // convention) must be named after the target's *actual* primary
        // key column, not a hardcoded `_id` suffix that wouldn't even
        // refer to a real column here.
        let mut schema = SchemaDefinition::new("s");
        let mut provider = ClassDefinition::new("Provider");
        let mut code = SlotDefinition::new("code");
        code.range = Some("string".to_string());
        code.identifier = true;
        provider.attributes.insert("code".to_string(), code);
        schema.classes.insert("Provider".to_string(), provider);

        let mut deployment = ClassDefinition::new("Deployment");
        let mut on_provider = SlotDefinition::new("on_provider");
        on_provider.range = Some("Provider".to_string());
        deployment
            .attributes
            .insert("on_provider".to_string(), on_provider);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"on_provider_code\" text"),
            "FK column must be named after the target's actual primary key column (`code`), not a hardcoded `_id`; got:\n{out}"
        );
        assert!(
            !out.contains("on_provider_id"),
            "must not also emit the old hardcoded `_id` suffix; got:\n{out}"
        );
        assert!(
            out.contains("REFERENCES \"provider\" (\"code\")"),
            "FK must reference the target's actual primary key column; got:\n{out}"
        );
    }

    #[test]
    fn abstract_class_emits_no_table() {
        let mut class = ClassDefinition::new("InfraComponent");
        class.r#abstract = true;
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE \"infra_component\""),
            "an abstract class must not get a table; got:\n{out}"
        );
    }

    #[test]
    fn mixin_attributes_are_flattened_into_the_mixing_class() {
        let mut auditable = ClassDefinition::new("Auditable");
        let mut created_at = SlotDefinition::new("created_at");
        created_at.range = Some("datetime".to_string());
        auditable
            .attributes
            .insert("created_at".to_string(), created_at);

        let mut deployment = ClassDefinition::new("Deployment");
        deployment.mixins = vec!["Auditable".to_string()];
        let mut status = SlotDefinition::new("status");
        status.range = Some("string".to_string());
        deployment.attributes.insert("status".to_string(), status);

        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert("Auditable".to_string(), auditable);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        let deployment_table = &out[out.find("CREATE TABLE \"deployment\" (").unwrap()..];
        assert!(
            deployment_table.contains("\"created_at\" timestamptz")
                && deployment_table.contains("\"status\" text"),
            "expected the mixin's attribute flattened alongside the class's own; got:\n{out}"
        );
        // The mixin, not being abstract, still gets its own table too.
        assert!(
            out.contains("CREATE TABLE \"auditable\" ("),
            "a non-abstract mixin still gets its own table; got:\n{out}"
        );
    }

    #[test]
    fn class_using_is_a_is_skipped_with_a_diagnostic() {
        let mut base = ClassDefinition::new("Base");
        base.r#abstract = true;
        let mut sub = ClassDefinition::new("Sub");
        sub.is_a = Some("Base".to_string());
        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert("Base".to_string(), base);
        schema.classes.insert("Sub".to_string(), sub);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE \"sub\""),
            "a class using is_a must not get a table yet; got:\n{out}"
        );
        let skipped = skipped_classes(&schema);
        assert_eq!(
            skipped,
            vec![SkippedClass {
                class: "Sub".to_string(),
                reason: "uses `is_a`, which this writer does not yet support".to_string(),
            }]
        );
    }

    #[test]
    fn class_with_multivalued_slot_is_skipped_with_a_diagnostic() {
        let mut class = ClassDefinition::new("Deployment");
        let mut tags = SlotDefinition::new("tags");
        tags.range = Some("string".to_string());
        tags.multivalued = true;
        class.attributes.insert("tags".to_string(), tags);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE \"deployment\""),
            "a class with a multivalued slot must not get a table yet; got:\n{out}"
        );
        assert_eq!(
            skipped_classes(&schema),
            vec![SkippedClass {
                class: "Deployment".to_string(),
                reason: "has multivalued slot `tags`, which this writer does not yet support"
                    .to_string(),
            }]
        );
    }

    #[test]
    fn class_with_any_of_slot_is_skipped_with_a_diagnostic() {
        let mut class = ClassDefinition::new("Input");
        let mut value = SlotDefinition::new("value");
        value.any_of = vec![SlotDefinition::new("a"), SlotDefinition::new("b")];
        class.attributes.insert("value".to_string(), value);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE \"input\""),
            "a class with an any_of slot must not get a table; got:\n{out}"
        );
        assert_eq!(
            skipped_classes(&schema),
            vec![SkippedClass {
                class: "Input".to_string(),
                reason:
                    "has polymorphic `any_of` slot `value`, which this writer does not yet support"
                        .to_string(),
            }]
        );
    }

    #[test]
    fn class_referencing_a_skipped_class_is_also_skipped() {
        let mut broken = ClassDefinition::new("Broken");
        broken.is_a = Some("Base".to_string());
        let mut base = ClassDefinition::new("Base");
        base.r#abstract = true;

        let mut deployment = ClassDefinition::new("Deployment");
        let mut broken_ref = SlotDefinition::new("broken_ref");
        broken_ref.range = Some("Broken".to_string());
        deployment
            .attributes
            .insert("broken_ref".to_string(), broken_ref);

        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert("Base".to_string(), base);
        schema.classes.insert("Broken".to_string(), broken);
        schema.classes.insert("Deployment".to_string(), deployment);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CREATE TABLE \"deployment\""),
            "a class referencing a skipped class must itself be skipped, not emit a broken FK; got:\n{out}"
        );
        let skipped = skipped_classes(&schema);
        assert!(
            skipped
                .iter()
                .any(|s| s.class == "Deployment" && s.reason.contains("Broken")),
            "expected Deployment skipped for referencing Broken; got: {skipped:?}"
        );
    }

    #[test]
    fn abstract_class_referencing_a_skipped_class_is_not_reported() {
        // Abstract classes are deliberately excluded from `skipped_classes`
        // (they get no table on purpose, which isn't a gap) — that must
        // hold even when the abstract class's own slot references another
        // class that IS a real gap (here, `Broken` uses `is_a`).
        let mut broken = ClassDefinition::new("Broken");
        broken.is_a = Some("Base".to_string());

        let mut abstract_class = ClassDefinition::new("AbstractThing");
        abstract_class.r#abstract = true;
        let mut broken_ref = SlotDefinition::new("broken_ref");
        broken_ref.range = Some("Broken".to_string());
        abstract_class
            .attributes
            .insert("broken_ref".to_string(), broken_ref);

        let mut schema = SchemaDefinition::new("s");
        schema.classes.insert("Broken".to_string(), broken);
        schema
            .classes
            .insert("AbstractThing".to_string(), abstract_class);

        let skipped = skipped_classes(&schema);
        assert!(
            !skipped.iter().any(|s| s.class == "AbstractThing"),
            "an abstract class must never appear in skipped_classes, even if its own slot references a real gap; got: {skipped:?}"
        );
        assert!(
            skipped.iter().any(|s| s.class == "Broken"),
            "Broken must still be reported for its own is_a usage; got: {skipped:?}"
        );
    }

    /// A representative multi-class fixture combining every construct this
    /// writer supports together — an enum, a synthesized uuid PK, an
    /// identifier-derived PK, and an FK between them.
    fn whole_script_fixture_schema() -> SchemaDefinition {
        use crate::linkml::{EnumDefinition, PermissibleValue};
        let mut schema = SchemaDefinition::new("nimbus");

        let mut status_enum = EnumDefinition::new("DeploymentStatus");
        status_enum
            .permissible_values
            .insert("actual".to_string(), PermissibleValue::new("actual"));
        status_enum
            .permissible_values
            .insert("planned".to_string(), PermissibleValue::new("planned"));
        schema
            .enums
            .insert("DeploymentStatus".to_string(), status_enum);

        // Provider: identifier-derived (non-synthetic) primary key.
        let mut provider = ClassDefinition::new("Provider");
        let mut code = SlotDefinition::new("code");
        code.range = Some("string".to_string());
        code.identifier = true;
        provider.attributes.insert("code".to_string(), code);
        schema.classes.insert("Provider".to_string(), provider);

        // Deployment: synthesized uuid primary key, an enum column, and
        // an FK to Provider's identifier-derived key.
        let mut deployment = ClassDefinition::new("Deployment");
        let mut status = SlotDefinition::new("status");
        status.range = Some("DeploymentStatus".to_string());
        status.required = true;
        deployment.attributes.insert("status".to_string(), status);
        let mut on_provider = SlotDefinition::new("on_provider");
        on_provider.range = Some("Provider".to_string());
        deployment
            .attributes
            .insert("on_provider".to_string(), on_provider);
        schema.classes.insert("Deployment".to_string(), deployment);

        schema
    }

    #[test]
    fn whole_script_with_enum_fk_and_both_pk_kinds_parses_as_one_unit() {
        // Parsed as one whole script (not per-statement), so a
        // statement-ordering mistake (e.g. a CREATE TYPE after the table
        // that needs it) would fail this even if each statement parsed
        // individually.
        let schema = whole_script_fixture_schema();

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        // Sanity that this fixture actually exercises what it claims to
        // (a failure here means the test stopped covering what its name
        // says, independent of whether pg_query accepts the output).
        assert!(out.contains("CREATE TYPE \"deployment_status\" AS ENUM"));
        assert!(out.contains("\"code\" text PRIMARY KEY"));
        assert!(out.contains("\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid()"));
        assert!(out.contains("ALTER TABLE \"deployment\" ADD CONSTRAINT"));
    }

    #[test]
    fn unique_keys_emit_a_table_level_unique_constraint() {
        use crate::linkml::UniqueKey;
        let mut class = ClassDefinition::new("Offering");
        let mut service_type = SlotDefinition::new("service_type");
        service_type.range = Some("string".to_string());
        class
            .attributes
            .insert("service_type".to_string(), service_type);
        let mut offered_by = SlotDefinition::new("offered_by");
        offered_by.range = Some("string".to_string());
        class
            .attributes
            .insert("offered_by".to_string(), offered_by);
        class.unique_keys.insert(
            "service_offering".to_string(),
            UniqueKey {
                unique_key_slots: vec!["service_type".to_string(), "offered_by".to_string()],
                description: None,
            },
        );
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains(
                "CONSTRAINT \"offering_service_offering_key\" UNIQUE (\"service_type\", \"offered_by\")"
            ),
            "expected a named table-level UNIQUE constraint over the key's slot tuple; got:\n{out}"
        );
    }

    #[test]
    fn pattern_emits_an_inline_check_constraint() {
        let mut class = ClassDefinition::new("Provider");
        let mut code = SlotDefinition::new("code");
        code.range = Some("string".to_string());
        code.pattern = Some("^[A-Z]{3}$".to_string());
        class.attributes.insert("code".to_string(), code);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"code\" text CHECK (\"code\" ~ '^[A-Z]{3}$')"),
            "expected an inline regex CHECK on the patterned column; got:\n{out}"
        );
    }

    #[test]
    fn pattern_single_quotes_are_escaped() {
        // A pattern containing a single quote must be doubled (`''`), or the
        // generated CHECK is a syntax error / injection. pg_query catches
        // it if we get this wrong.
        let mut class = ClassDefinition::new("Note");
        let mut body = SlotDefinition::new("body");
        body.range = Some("string".to_string());
        body.pattern = Some("it's".to_string());
        class.attributes.insert("body".to_string(), body);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("CHECK (\"body\" ~ 'it''s')"),
            "single quotes in a pattern must be doubled; got:\n{out}"
        );
    }

    #[test]
    fn both_value_bounds_emit_one_combined_check() {
        let mut class = ClassDefinition::new("Reading");
        let mut level = SlotDefinition::new("level");
        level.range = Some("integer".to_string());
        level.minimum_value = Some(0.0);
        level.maximum_value = Some(100.0);
        class.attributes.insert("level".to_string(), level);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"level\" integer CHECK (\"level\" >= 0 AND \"level\" <= 100)"),
            "both bounds must combine into one CHECK; got:\n{out}"
        );
    }

    #[test]
    fn a_single_value_bound_emits_only_that_side() {
        let mut class = ClassDefinition::new("Reading");
        let mut ratio = SlotDefinition::new("ratio");
        ratio.range = Some("float".to_string());
        ratio.minimum_value = Some(0.0);
        class.attributes.insert("ratio".to_string(), ratio);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"ratio\" double precision CHECK (\"ratio\" >= 0)"),
            "a lone minimum_value must emit only the `>=` side; got:\n{out}"
        );
        assert!(
            !out.contains("<="),
            "no maximum_value set, so no `<=` clause; got:\n{out}"
        );
    }

    #[test]
    fn a_lone_maximum_value_emits_only_the_upper_bound() {
        let mut class = ClassDefinition::new("Reading");
        let mut ratio = SlotDefinition::new("ratio");
        ratio.range = Some("float".to_string());
        ratio.maximum_value = Some(1.0);
        class.attributes.insert("ratio".to_string(), ratio);
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains("\"ratio\" double precision CHECK (\"ratio\" <= 1)"),
            "a lone maximum_value must emit only the `<=` side; got:\n{out}"
        );
        assert!(
            !out.contains(">="),
            "no minimum_value set, so no `>=` clause; got:\n{out}"
        );
    }

    /// A class with a conditional rule: when `status` = `actual`, `region`
    /// is required. Both slots are plain strings so the emitted predicates
    /// are text comparisons (no enum setup needed).
    fn class_with_conditional_rule() -> ClassDefinition {
        use crate::linkml::{ClassRule, RuleConditions, SlotCondition};
        let mut class = ClassDefinition::new("Deployment");
        let mut status = SlotDefinition::new("status");
        status.range = Some("string".to_string());
        class.attributes.insert("status".to_string(), status);
        let mut region = SlotDefinition::new("region");
        region.range = Some("string".to_string());
        class.attributes.insert("region".to_string(), region);

        let pre = SlotCondition {
            equals_string: Some("actual".to_string()),
            ..Default::default()
        };
        let post = SlotCondition {
            required: true,
            ..Default::default()
        };
        class.rules.push(ClassRule {
            title: Some("actual-needs-region".to_string()),
            description: None,
            preconditions: Some(RuleConditions {
                slot_conditions: [("status".to_string(), pre)].into_iter().collect(),
            }),
            postconditions: Some(RuleConditions {
                slot_conditions: [("region".to_string(), post)].into_iter().collect(),
            }),
        });
        class
    }

    #[test]
    fn a_rule_emits_a_conditional_check_constraint() {
        let schema = schema_with_class(class_with_conditional_rule());

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            out.contains(
                "CONSTRAINT \"deployment_rule0_check\" CHECK (NOT (\"status\" = 'actual') OR (\"region\" IS NOT NULL))"
            ),
            "expected the conditional rule encoded as NOT(pre) OR (post); got:\n{out}"
        );
    }

    #[test]
    fn an_expressible_rule_is_not_reported_as_skipped() {
        let schema = schema_with_class(class_with_conditional_rule());
        assert!(
            skipped_rules(&schema).is_empty(),
            "a fully expressible rule must not be reported as skipped; got: {:?}",
            skipped_rules(&schema)
        );
    }

    #[test]
    fn a_one_sided_rule_is_skipped_with_a_diagnostic() {
        use crate::linkml::{ClassRule, RuleConditions, SlotCondition};
        let mut class = ClassDefinition::new("Deployment");
        let mut status = SlotDefinition::new("status");
        status.range = Some("string".to_string());
        class.attributes.insert("status".to_string(), status);
        let pre = SlotCondition {
            equals_string: Some("actual".to_string()),
            ..Default::default()
        };
        class.rules.push(ClassRule {
            title: Some("dangling".to_string()),
            description: None,
            preconditions: Some(RuleConditions {
                slot_conditions: [("status".to_string(), pre)].into_iter().collect(),
            }),
            postconditions: None,
        });
        let schema = schema_with_class(class);

        // Not emitted...
        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CHECK"),
            "a one-sided rule emits no CHECK; got:\n{out}"
        );
        // ...and reported, named by its title.
        let skipped = skipped_rules(&schema);
        assert_eq!(skipped.len(), 1, "got: {skipped:?}");
        assert_eq!(skipped[0].class, "Deployment");
        assert_eq!(skipped[0].rule, "dangling");
    }

    #[test]
    fn a_rule_with_a_range_condition_is_skipped_and_labeled_by_index() {
        // `range` has no single-column CHECK form, so the rule is
        // unexpressible; with no title it's labeled by position.
        use crate::linkml::{ClassRule, RuleConditions, SlotCondition};
        let mut class = ClassDefinition::new("Deployment");
        let mut status = SlotDefinition::new("status");
        status.range = Some("string".to_string());
        class.attributes.insert("status".to_string(), status);
        let mut region = SlotDefinition::new("region");
        region.range = Some("string".to_string());
        class.attributes.insert("region".to_string(), region);
        let pre = SlotCondition {
            equals_string: Some("actual".to_string()),
            ..Default::default()
        };
        let post = SlotCondition {
            range: Some("SomeType".to_string()), // not CHECK-able
            ..Default::default()
        };
        class.rules.push(ClassRule {
            title: None,
            description: None,
            preconditions: Some(RuleConditions {
                slot_conditions: [("status".to_string(), pre)].into_iter().collect(),
            }),
            postconditions: Some(RuleConditions {
                slot_conditions: [("region".to_string(), post)].into_iter().collect(),
            }),
        });
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CHECK (NOT"),
            "unexpressible rule emits no CHECK; got:\n{out}"
        );
        let skipped = skipped_rules(&schema);
        assert_eq!(skipped.len(), 1, "got: {skipped:?}");
        assert_eq!(skipped[0].rule, "rule #0", "untitled rule labeled by index");
    }

    #[test]
    fn a_rule_naming_a_missing_slot_is_skipped() {
        use crate::linkml::{ClassRule, RuleConditions, SlotCondition};
        let mut class = ClassDefinition::new("Deployment");
        let mut status = SlotDefinition::new("status");
        status.range = Some("string".to_string());
        class.attributes.insert("status".to_string(), status);
        let pre = SlotCondition {
            equals_string: Some("actual".to_string()),
            ..Default::default()
        };
        let post = SlotCondition {
            required: true,
            ..Default::default()
        };
        class.rules.push(ClassRule {
            title: Some("ghost-ref".to_string()),
            description: None,
            preconditions: Some(RuleConditions {
                slot_conditions: [("status".to_string(), pre)].into_iter().collect(),
            }),
            postconditions: Some(RuleConditions {
                slot_conditions: [("ghost".to_string(), post)].into_iter().collect(),
            }),
        });
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("ghost"),
            "no column for the missing slot; got:\n{out}"
        );
        assert_eq!(skipped_rules(&schema).len(), 1);
    }

    /// A rule whose postcondition pairs an expressible field (`required`)
    /// with `cond`'s unexpressible field. Used to pin each disjunct of the
    /// "no single-column CHECK form" guard: the expressible field alone
    /// would emit, so the rule is skipped *only* because the guard treats
    /// the unexpressible field as disqualifying (OR, not AND).
    fn schema_with_rule_postcondition(cond: crate::linkml::SlotCondition) -> SchemaDefinition {
        use crate::linkml::{ClassRule, RuleConditions, SlotCondition};
        let mut class = ClassDefinition::new("Deployment");
        let mut status = SlotDefinition::new("status");
        status.range = Some("string".to_string());
        class.attributes.insert("status".to_string(), status);
        let mut region = SlotDefinition::new("region");
        region.range = Some("string".to_string());
        class.attributes.insert("region".to_string(), region);
        let pre = SlotCondition {
            equals_string: Some("actual".to_string()),
            ..Default::default()
        };
        class.rules.push(ClassRule {
            title: Some("r".to_string()),
            description: None,
            preconditions: Some(RuleConditions {
                slot_conditions: [("status".to_string(), pre)].into_iter().collect(),
            }),
            postconditions: Some(RuleConditions {
                slot_conditions: [("region".to_string(), cond)].into_iter().collect(),
            }),
        });
        schema_with_class(class)
    }

    #[test]
    fn a_rule_condition_mixing_required_with_min_cardinality_is_skipped() {
        // `minimum_cardinality` has no single-column CHECK form, so even
        // paired with an expressible `required` the whole rule is skipped —
        // the guard is a disjunction (any unexpressible field disqualifies).
        let schema = schema_with_rule_postcondition(crate::linkml::SlotCondition {
            required: true,
            minimum_cardinality: Some(1),
            ..Default::default()
        });
        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CHECK (NOT"),
            "rule must be skipped; got:\n{out}"
        );
        assert_eq!(skipped_rules(&schema).len(), 1, "and reported as skipped");
    }

    #[test]
    fn a_rule_condition_mixing_required_with_max_cardinality_is_skipped() {
        let schema = schema_with_rule_postcondition(crate::linkml::SlotCondition {
            required: true,
            maximum_cardinality: Some(1),
            ..Default::default()
        });
        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("CHECK (NOT"),
            "rule must be skipped; got:\n{out}"
        );
        assert_eq!(skipped_rules(&schema).len(), 1, "and reported as skipped");
    }

    #[test]
    fn an_abstract_class_contributes_no_rule_diagnostics() {
        // An abstract class gets no table at all, so its rules are moot —
        // `skipped_rules` must not report them (that omission is covered by
        // the class getting no table, not a per-rule warning).
        use crate::linkml::{ClassRule, RuleConditions, SlotCondition};
        let mut class = ClassDefinition::new("AbstractThing");
        class.r#abstract = true;
        let mut status = SlotDefinition::new("status");
        status.range = Some("string".to_string());
        class.attributes.insert("status".to_string(), status);
        let pre = SlotCondition {
            equals_string: Some("actual".to_string()),
            ..Default::default()
        };
        class.rules.push(ClassRule {
            title: Some("moot".to_string()),
            description: None,
            preconditions: Some(RuleConditions {
                slot_conditions: [("status".to_string(), pre)].into_iter().collect(),
            }),
            postconditions: None, // one-sided → would be "skipped" if it had a table
        });
        let schema = schema_with_class(class);
        assert!(
            skipped_rules(&schema).is_empty(),
            "an abstract class's rules must not be reported; got: {:?}",
            skipped_rules(&schema)
        );
    }

    #[test]
    fn a_table_less_class_contributes_no_rule_diagnostics() {
        // A class skipped for `is_a` (no table) likewise contributes no
        // per-rule diagnostics — its whole omission is `skipped_classes`.
        use crate::linkml::{ClassRule, RuleConditions, SlotCondition};
        let mut class = ClassDefinition::new("Sub");
        class.is_a = Some("Base".to_string());
        let mut status = SlotDefinition::new("status");
        status.range = Some("string".to_string());
        class.attributes.insert("status".to_string(), status);
        let pre = SlotCondition {
            equals_string: Some("actual".to_string()),
            ..Default::default()
        };
        class.rules.push(ClassRule {
            title: Some("moot".to_string()),
            description: None,
            preconditions: Some(RuleConditions {
                slot_conditions: [("status".to_string(), pre)].into_iter().collect(),
            }),
            postconditions: None,
        });
        let schema = schema_with_class(class);
        assert!(
            skipped_rules(&schema).is_empty(),
            "a table-less (is_a-skipped) class's rules must not be reported; got: {:?}",
            skipped_rules(&schema)
        );
    }

    #[test]
    fn unique_key_naming_a_missing_slot_is_dropped_not_emitted() {
        // A key referencing a slot the class doesn't have must not emit a
        // UNIQUE clause naming a nonexistent column (which would be broken
        // DDL). The CLI separately warns about it via
        // `diagnostics::unresolved_unique_key_slots`; the writer itself
        // must still never emit broken SQL even if that warning is ignored.
        use crate::linkml::UniqueKey;
        let mut class = ClassDefinition::new("Offering");
        let mut service_type = SlotDefinition::new("service_type");
        service_type.range = Some("string".to_string());
        class
            .attributes
            .insert("service_type".to_string(), service_type);
        class.unique_keys.insert(
            "bad_key".to_string(),
            UniqueKey {
                unique_key_slots: vec!["service_type".to_string(), "ghost".to_string()],
                description: None,
            },
        );
        let schema = schema_with_class(class);

        let out = PostgresWriter::new().render(&schema);
        assert_valid_postgres_sql(&out);
        assert!(
            !out.contains("ghost"),
            "a key naming a slot the class lacks must not appear in the DDL; got:\n{out}"
        );
        assert!(
            !out.contains("bad_key"),
            "a key with an unresolved slot must be dropped entirely, not emitted partially; got:\n{out}"
        );
    }

    #[test]
    #[ignore = "needs Docker; run with `cargo nextest run -p panschema --features dev --run-ignored=only -E 'test(postgres_apply)'`"]
    fn postgres_apply_applies_generated_ddl_to_a_real_database() {
        // pg_query (above) proves the DDL is syntactically valid Postgres;
        // it can't catch a semantic error like an FK column whose type
        // doesn't match its target's real primary key. Applying the DDL
        // against a real, disposable Postgres container is the oracle
        // that would.
        use testcontainers_modules::postgres::Postgres;
        use testcontainers_modules::testcontainers::ImageExt;
        use testcontainers_modules::testcontainers::runners::SyncRunner;

        let ddl = PostgresWriter::new().render(&whole_script_fixture_schema());

        // Pinned rather than the module's own default (Postgres 11):
        // `gen_random_uuid()` — used for every synthesized primary key —
        // is only built into Postgres 13+, so testing against an older
        // default would fail on this writer's own generated DDL.
        let node = Postgres::default()
            .with_tag("16-alpine")
            .start()
            .expect("failed to start Postgres container");
        let port = node
            .get_host_port_ipv4(5432)
            .expect("failed to get container's mapped port");
        let connection_string = format!("postgres://postgres:postgres@127.0.0.1:{port}/postgres");
        let mut client = postgres::Client::connect(&connection_string, postgres::NoTls)
            .expect("failed to connect to Postgres container");

        client.batch_execute(&ddl).unwrap_or_else(|e| {
            panic!("generated DDL failed to apply to a real Postgres database: {e}\n\nDDL:\n{ddl}")
        });
    }
}
