//! Rust code generator for LinkML schemas.
//!
//! Emits a single flat Rust module per schema, suitable for `include!()`
//! or `pub mod` use in a downstream crate. See
//! [docs/features/05-schema-manager.md](../../docs/features/05-schema-manager.md)
//! and the planning note at
//! `~/.claude/plans/scalable-crunching-hedgehog.md`.
//!
//! Slice 6.1 — stub. Emits only the `// @generated by panschema v<version>`
//! header line. Subsequent slices fill in struct/enum/trait codegen.

use std::path::Path;

use crate::io::{IoError, IoResult, Writer};
use crate::linkml::SchemaDefinition;

/// Writes a Rust module representing the schema's classes, enums, and
/// inheritance structure.
#[derive(Debug, Default)]
pub struct RustWriter;

impl RustWriter {
    pub fn new() -> Self {
        Self
    }

    /// Produce the generated Rust source text for `schema`.
    ///
    /// Separating render-to-string from `write` makes the unit tests
    /// simpler (no tempdir needed) and lets future slices snapshot
    /// the output via `insta`.
    pub fn render(&self, schema: &SchemaDefinition) -> String {
        let mut out = String::new();
        write_header(&mut out, schema);
        out
    }
}

impl Writer for RustWriter {
    fn write(&self, schema: &SchemaDefinition, output: &Path) -> IoResult<()> {
        if let Some(parent) = output.parent()
            && !parent.as_os_str().is_empty()
        {
            std::fs::create_dir_all(parent).map_err(IoError::Io)?;
        }
        std::fs::write(output, self.render(schema)).map_err(IoError::Io)?;
        Ok(())
    }

    fn format_id(&self) -> &str {
        "rust"
    }
}

fn write_header(out: &mut String, schema: &SchemaDefinition) {
    let version = env!("CARGO_PKG_VERSION");
    out.push_str(&format!("// @generated by panschema v{version}\n"));
    out.push_str(&format!("// Schema: {}\n", schema.name));
    if let Some(v) = &schema.version {
        out.push_str(&format!("// Schema version: {v}\n"));
    }
    out.push_str("// Do not hand-edit; re-run `panschema generate` to refresh.\n");
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::linkml::SchemaDefinition;

    #[test]
    fn renders_generated_marker_with_panschema_version() {
        let mut schema = SchemaDefinition::new("demo");
        schema.version = Some("0.1.0".to_string());

        let out = RustWriter::new().render(&schema);
        let expected_version = env!("CARGO_PKG_VERSION");
        assert!(
            out.contains(&format!("// @generated by panschema v{expected_version}")),
            "missing generated marker; got:\n{out}"
        );
        assert!(out.contains("// Schema: demo"));
        assert!(out.contains("// Schema version: 0.1.0"));
    }

    #[test]
    fn omits_schema_version_line_when_unspecified() {
        let schema = SchemaDefinition::new("demo");
        // schema.version stays None
        let out = RustWriter::new().render(&schema);
        assert!(!out.contains("// Schema version:"), "got: {out}");
    }

    #[test]
    fn format_id_is_rust() {
        assert_eq!(RustWriter::new().format_id(), "rust");
    }

    #[test]
    fn write_creates_parent_dirs() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path().join("nested").join("dir").join("out.rs");
        let schema = SchemaDefinition::new("demo");

        RustWriter::new().write(&schema, &target).unwrap();
        assert!(target.exists());
        let body = std::fs::read_to_string(&target).unwrap();
        assert!(body.contains("@generated by panschema"));
    }
}
