//! Rust code generator for LinkML schemas.
//!
//! Emits a single flat Rust module per schema, suitable for `include!()`
//! or `pub mod` use in a downstream crate. See
//! [docs/features/06-rust-codegen.md](../../docs/features/06-rust-codegen.md)
//! for the LinkML → Rust mapping and the broader roadmap.
//!
//! Generated code depends on `serde` (for `Serialize`/`Deserialize` derives)
//! and `chrono` (for `DateTime<Utc>` when a slot's range is `datetime`).
//! The consumer declares those in their own `Cargo.toml`; panschema
//! itself doesn't take chrono.

use std::path::Path;

use crate::io::{IoError, IoResult, Writer};
use crate::linkml::{ClassDefinition, EnumDefinition, SchemaDefinition, SlotDefinition};

/// Writes a Rust module representing the schema's classes, enums, and
/// inheritance structure.
#[derive(Debug, Default)]
pub struct RustWriter;

impl RustWriter {
    pub fn new() -> Self {
        Self
    }

    /// Produce the generated Rust source text for `schema`.
    ///
    /// Separating render-to-string from `write` keeps unit tests simple
    /// (no tempdir or filesystem state needed) and leaves the door open
    /// for snapshot-based testing.
    pub fn render(&self, schema: &SchemaDefinition) -> String {
        let mut out = String::new();
        render_header(&mut out, schema);
        // Enums first so a class's `range: EnumName` always refers to a
        // type that's already in scope when rustc reads top-to-bottom.
        // BTreeMap iteration is sorted by key, so output is deterministic.
        for (name, def) in &schema.enums {
            render_enum(&mut out, name, def);
        }
        for (name, def) in &schema.classes {
            render_class(&mut out, name, def, schema);
        }
        out
    }
}

impl Writer for RustWriter {
    fn write(&self, schema: &SchemaDefinition, output: &Path) -> IoResult<()> {
        if let Some(parent) = output.parent()
            && !parent.as_os_str().is_empty()
        {
            std::fs::create_dir_all(parent).map_err(IoError::Io)?;
        }
        std::fs::write(output, self.render(schema)).map_err(IoError::Io)?;
        Ok(())
    }

    fn format_id(&self) -> &str {
        "rust"
    }
}

// ---------------------------------------------------------------------------
// Top-level renderers
// ---------------------------------------------------------------------------

fn render_header(out: &mut String, schema: &SchemaDefinition) {
    let version = env!("CARGO_PKG_VERSION");
    out.push_str(&format!("// @generated by panschema v{version}\n"));
    out.push_str(&format!("// Schema: {}\n", schema.name));
    if let Some(v) = &schema.version {
        out.push_str(&format!("// Schema version: {v}\n"));
    }
    out.push_str("// Do not hand-edit; re-run `panschema generate` to refresh.\n");
    out.push_str("\n#![allow(non_camel_case_types, non_snake_case, dead_code)]\n");
    out.push('\n');
}

fn render_enum(out: &mut String, name: &str, def: &EnumDefinition) {
    render_doc_comment(out, "", def.description.as_deref());
    out.push_str(
        "#[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]\n",
    );
    out.push_str(&format!("pub enum {name} {{\n"));
    // BTreeMap iteration is sorted — variant order is deterministic.
    for (key, value) in &def.permissible_values {
        let text = if value.text.is_empty() {
            key
        } else {
            &value.text
        };
        render_doc_comment(out, "    ", value.description.as_deref());
        let variant_ident = variant_ident_for(text);
        if variant_ident == *text {
            // Identifier already matches the wire value; rename is redundant.
            out.push_str(&format!("    {variant_ident},\n"));
        } else {
            out.push_str(&format!(
                "    #[serde(rename = \"{}\")]\n",
                escape_str(text)
            ));
            out.push_str(&format!("    {variant_ident},\n"));
        }
    }
    out.push_str("}\n\n");
}

fn render_class(out: &mut String, name: &str, def: &ClassDefinition, schema: &SchemaDefinition) {
    render_doc_comment(out, "", def.description.as_deref());
    if def.r#abstract {
        out.push_str("///\n/// LinkML abstract class.\n");
    }
    out.push_str("#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));

    for (slot_name, slot) in direct_slots(def, schema) {
        let rust_field = snake_case(&slot_name);
        let rust_type = rust_type_for(slot, schema);
        render_doc_comment(out, "    ", slot.description.as_deref());

        let mut serde_attrs: Vec<String> = Vec::new();
        if rust_field != slot_name {
            serde_attrs.push(format!("rename = \"{}\"", escape_str(&slot_name)));
        }
        // Optional (non-multivalued, non-required) slots skip serializing
        // `None` so the LinkML wire format doesn't carry explicit nulls.
        if !slot.required && !slot.multivalued {
            serde_attrs.push("default".to_string());
            serde_attrs.push("skip_serializing_if = \"Option::is_none\"".to_string());
        } else if slot.multivalued {
            // Empty `Vec` is the natural default for multivalued slots —
            // a missing key in the wire format means "no values."
            serde_attrs.push("default".to_string());
            serde_attrs.push("skip_serializing_if = \"Vec::is_empty\"".to_string());
        }
        if !serde_attrs.is_empty() {
            out.push_str(&format!("    #[serde({})]\n", serde_attrs.join(", ")));
        }
        out.push_str(&format!("    pub {rust_field}: {rust_type},\n"));
    }

    out.push_str("}\n\n");
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Returns the slots defined *directly* on this class — its inline
/// `attributes` plus any global `slots:` references resolved against the
/// schema. Slots inherited via `is_a` or `mixins`, and `slot_usage`
/// refinements, are not included here.
///
/// Returns a `Vec` of `(slot_name, &SlotDefinition)` sorted alphabetically
/// by slot name. Sorting (rather than honouring `class.slots`'s array
/// order) keeps the generated Rust output deterministic across runs and
/// across LinkML files whose authors used different orderings for the
/// same set of slots.
fn direct_slots<'a>(
    class: &'a ClassDefinition,
    schema: &'a SchemaDefinition,
) -> Vec<(String, &'a SlotDefinition)> {
    let mut collected: Vec<(String, &SlotDefinition)> = Vec::new();
    for (name, def) in &class.attributes {
        collected.push((name.clone(), def));
    }
    // Global slots referenced by name. Unresolved refs are silently
    // dropped; a future error path could surface them as a writer-level
    // diagnostic.
    for slot_name in &class.slots {
        if let Some(def) = schema.slots.get(slot_name) {
            collected.push((slot_name.clone(), def));
        }
    }
    // De-dup by slot name (attributes win over a same-named global slot ref).
    collected.sort_by(|a, b| a.0.cmp(&b.0));
    collected.dedup_by(|a, b| a.0 == b.0);
    collected
}

/// Map a LinkML slot definition to its Rust field type. Applies
/// required/multivalued framing: `Vec<T>` if multivalued, `Option<T>` if
/// optional and single, bare `T` if required and single.
///
/// `schema` is unused at this layer today but is threaded through so the
/// signature stays stable once polymorphic ranges and `slot_usage`
/// resolution land.
fn rust_type_for(slot: &SlotDefinition, _schema: &SchemaDefinition) -> String {
    let base = base_type_for_range(slot.range.as_deref());
    if slot.multivalued {
        format!("Vec<{base}>")
    } else if slot.required {
        base
    } else {
        format!("Option<{base}>")
    }
}

/// The unwrapped Rust type for a single LinkML range value (before
/// applying `Vec` / `Option` framing).
///
/// LinkML's built-in type vocabulary maps to Rust primitives; everything
/// else is treated as a reference to a class, enum, or imported type and
/// emitted as a bare type name. Unknown ranges fall back to `String` —
/// LinkML's `default_range` is conventionally `string` anyway.
fn base_type_for_range(range: Option<&str>) -> String {
    let Some(range) = range else {
        return "String".to_string();
    };
    match range {
        "string" | "str" | "uri" | "uriorcurie" | "curie" | "ncname" | "objectidentifier"
        | "nodeidentifier" => "String".to_string(),
        "integer" | "int" => "i64".to_string(),
        "boolean" | "bool" => "bool".to_string(),
        "float" | "double" | "decimal" => "f64".to_string(),
        "datetime" => "chrono::DateTime<chrono::Utc>".to_string(),
        "date" => "chrono::NaiveDate".to_string(),
        "time" => "chrono::NaiveTime".to_string(),
        other => other.to_string(),
    }
}

/// Convert a LinkML identifier (typically lowerCamelCase) to snake_case
/// for use as a Rust field name. Lowercases existing characters and
/// inserts `_` before each uppercase letter that follows a lowercase one
/// or a digit. Handles consecutive uppercase by treating runs as a single
/// "word" (so `URL_path` → `url_path`, not `u_r_l_path`).
///
/// Examples:
/// - `wasGeneratedBy` → `was_generated_by`
/// - `id` → `id`
/// - `URL` → `url`
/// - `parseHTTPRequest` → `parse_http_request`
/// - `already_snake` → `already_snake`
pub fn snake_case(name: &str) -> String {
    let chars: Vec<char> = name.chars().collect();
    let mut out = String::with_capacity(name.len() + 4);

    for (i, &c) in chars.iter().enumerate() {
        if c == '_' {
            out.push('_');
            continue;
        }
        if c.is_ascii_uppercase() {
            let prev = if i == 0 { None } else { Some(chars[i - 1]) };
            let next = chars.get(i + 1).copied();
            let prev_is_lower_or_digit =
                prev.is_some_and(|p| p.is_ascii_lowercase() || p.is_ascii_digit());
            let prev_is_upper = prev.is_some_and(|p| p.is_ascii_uppercase());
            let next_is_lower = next.is_some_and(|n| n.is_ascii_lowercase());
            // Insert `_` before this char when transitioning from a
            // lowercase/digit run *or* when this is the start of a new
            // CamelCase word inside a run of uppercase letters
            // (e.g. the `R` in `parseHTTPRequest`).
            let needs_underscore = i > 0
                && !out.ends_with('_')
                && (prev_is_lower_or_digit || (prev_is_upper && next_is_lower));
            if needs_underscore {
                out.push('_');
            }
            for lower in c.to_lowercase() {
                out.push(lower);
            }
        } else {
            out.push(c);
        }
    }
    out
}

/// Emit a LinkML description as Rust doc comment lines. Each output line
/// is `<indent>/// <text>\n`. Lines are wrapped at a soft 80-column
/// boundary (76 chars of content + 4 chars of `/// ` prefix), breaking
/// on word boundaries.
fn render_doc_comment(out: &mut String, indent: &str, description: Option<&str>) {
    let Some(text) = description else { return };
    if text.is_empty() {
        return;
    }
    const WIDTH: usize = 76;
    // Pre-existing line breaks in the LinkML description are honored —
    // each line is wrapped independently so the writer doesn't munge
    // markdown paragraphs into one giant blob.
    for paragraph in text.split('\n') {
        if paragraph.is_empty() {
            out.push_str(indent);
            out.push_str("///\n");
            continue;
        }
        let mut current = String::new();
        for word in paragraph.split_whitespace() {
            if current.is_empty() {
                current.push_str(word);
            } else if current.len() + 1 + word.len() > WIDTH {
                out.push_str(indent);
                out.push_str("/// ");
                out.push_str(&current);
                out.push('\n');
                current.clear();
                current.push_str(word);
            } else {
                current.push(' ');
                current.push_str(word);
            }
        }
        if !current.is_empty() {
            out.push_str(indent);
            out.push_str("/// ");
            out.push_str(&current);
            out.push('\n');
        }
    }
}

/// Escape a `"` and `\` in a string for embedding inside a Rust string
/// literal (used in `#[serde(rename = "...")]` attributes).
fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

/// Sanitize a LinkML enum permissible-value text into a valid Rust
/// identifier suitable for use as an enum variant. Strips characters that
/// aren't `[A-Za-z0-9_]` and prepends `_` if the result starts with a
/// digit. If the input is already a valid identifier, returns it
/// unchanged so the serde `rename` attribute can be skipped.
fn variant_ident_for(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        if c.is_ascii_alphanumeric() || c == '_' {
            out.push(c);
        } else if c == '-' || c == ' ' {
            out.push('_');
        }
        // silently drop other characters
    }
    if out.is_empty() {
        out.push('_');
    }
    if out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        out.insert(0, '_');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::linkml::{ClassDefinition, EnumDefinition, PermissibleValue, SlotDefinition};

    // ----- snake_case --------------------------------------------------

    #[test]
    fn snake_case_lower_camel() {
        assert_eq!(snake_case("wasGeneratedBy"), "was_generated_by");
    }

    #[test]
    fn snake_case_already_snake() {
        assert_eq!(snake_case("already_snake"), "already_snake");
    }

    #[test]
    fn snake_case_single_lowercase() {
        assert_eq!(snake_case("id"), "id");
    }

    #[test]
    fn snake_case_all_caps_acronym() {
        assert_eq!(snake_case("URL"), "url");
    }

    #[test]
    fn snake_case_internal_acronym() {
        assert_eq!(snake_case("parseHTTPRequest"), "parse_http_request");
    }

    #[test]
    fn snake_case_with_digit() {
        assert_eq!(snake_case("foo2Bar"), "foo2_bar");
    }

    // ----- rust_type_for ----------------------------------------------

    fn slot(range: Option<&str>, required: bool, multivalued: bool) -> SlotDefinition {
        let mut s = SlotDefinition::new("test");
        s.range = range.map(str::to_string);
        s.required = required;
        s.multivalued = multivalued;
        s
    }

    #[test]
    fn rust_type_required_string() {
        let schema = SchemaDefinition::new("s");
        assert_eq!(
            rust_type_for(&slot(Some("string"), true, false), &schema),
            "String"
        );
    }

    #[test]
    fn rust_type_optional_integer() {
        let schema = SchemaDefinition::new("s");
        assert_eq!(
            rust_type_for(&slot(Some("integer"), false, false), &schema),
            "Option<i64>"
        );
    }

    #[test]
    fn rust_type_multivalued_boolean_overrides_required_framing() {
        let schema = SchemaDefinition::new("s");
        // Even when required, multivalued wins → Vec<T>. LinkML's
        // required+multivalued semantics ("must have at least one")
        // are enforced at runtime, not in the type system.
        assert_eq!(
            rust_type_for(&slot(Some("boolean"), true, true), &schema),
            "Vec<bool>"
        );
    }

    #[test]
    fn rust_type_datetime_maps_to_chrono() {
        let schema = SchemaDefinition::new("s");
        assert_eq!(
            rust_type_for(&slot(Some("datetime"), true, false), &schema),
            "chrono::DateTime<chrono::Utc>"
        );
    }

    #[test]
    fn rust_type_class_reference() {
        let mut schema = SchemaDefinition::new("s");
        schema
            .classes
            .insert("Question".to_string(), ClassDefinition::new("Question"));
        assert_eq!(
            rust_type_for(&slot(Some("Question"), false, false), &schema),
            "Option<Question>"
        );
    }

    #[test]
    fn rust_type_missing_range_defaults_to_string() {
        let schema = SchemaDefinition::new("s");
        assert_eq!(rust_type_for(&slot(None, true, false), &schema), "String");
    }

    // ----- doc comments -----------------------------------------------

    #[test]
    fn doc_comment_renders_single_line() {
        let mut out = String::new();
        render_doc_comment(&mut out, "", Some("A class."));
        assert_eq!(out, "/// A class.\n");
    }

    #[test]
    fn doc_comment_wraps_long_lines() {
        let mut out = String::new();
        let long = "This is a long description that should wrap at a soft eighty-column boundary because Rust idiom keeps doc comments readable.";
        render_doc_comment(&mut out, "", Some(long));
        // Every line in the output begins with `/// ` (the doc-comment
        // prefix). Asserting the per-line ≤ 80-char width keeps the
        // generated output readable.
        for line in out.lines() {
            assert!(line.starts_with("/// "), "missing prefix: {line}");
            assert!(line.len() <= 80, "line too long ({}): {line}", line.len());
        }
        // The full content round-trips.
        let stripped = out
            .lines()
            .map(|l| l.trim_start_matches("/// "))
            .collect::<Vec<_>>()
            .join(" ");
        assert_eq!(stripped, long);
    }

    #[test]
    fn doc_comment_respects_blank_lines() {
        let mut out = String::new();
        render_doc_comment(&mut out, "", Some("First paragraph.\n\nSecond paragraph."));
        assert_eq!(out, "/// First paragraph.\n///\n/// Second paragraph.\n");
    }

    #[test]
    fn doc_comment_skipped_when_description_missing() {
        let mut out = String::new();
        render_doc_comment(&mut out, "", None);
        assert_eq!(out, "");
    }

    // ----- enum rendering ---------------------------------------------

    #[test]
    fn render_enum_emits_variants_in_sorted_order() {
        let mut def = EnumDefinition::new("UncertaintyNature");
        def.description = Some("The nature of an uncertainty.".to_string());
        def.permissible_values.insert("Aleatory".to_string(), {
            let mut pv = PermissibleValue::new("Aleatory");
            pv.description = Some("Inherent randomness.".to_string());
            pv
        });
        def.permissible_values
            .insert("Epistemic".to_string(), PermissibleValue::new("Epistemic"));

        let mut out = String::new();
        render_enum(&mut out, "UncertaintyNature", &def);

        assert!(out.contains("pub enum UncertaintyNature"));
        // BTreeMap orders Aleatory < Epistemic alphabetically.
        let aleatory_pos = out.find("Aleatory").unwrap();
        let epistemic_pos = out.find("Epistemic").unwrap();
        assert!(aleatory_pos < epistemic_pos, "variants not sorted: {out}");
        // Aleatory has a description → emit a doc comment.
        assert!(
            out.contains("/// Inherent randomness."),
            "missing variant doc: {out}"
        );
        // Variant text already matches the identifier → no rename needed.
        assert!(
            !out.contains(r#"rename = "Aleatory""#),
            "redundant rename: {out}"
        );
    }

    #[test]
    fn render_enum_adds_serde_rename_when_text_is_not_a_valid_ident() {
        let mut def = EnumDefinition::new("Color");
        def.permissible_values
            .insert("off-white".to_string(), PermissibleValue::new("off-white"));

        let mut out = String::new();
        render_enum(&mut out, "Color", &def);

        assert!(out.contains("off_white"), "ident not sanitized: {out}");
        assert!(
            out.contains(r#"rename = "off-white""#),
            "missing serde rename: {out}"
        );
    }

    // ----- class rendering --------------------------------------------

    #[test]
    fn render_class_emits_struct_with_inline_attributes() {
        let mut def = ClassDefinition::new("Question");
        def.description = Some("A scientific question.".to_string());
        let mut label = SlotDefinition::new("label");
        label.range = Some("string".to_string());
        label.required = true;
        label.description = Some("Human-readable label.".to_string());
        def.attributes.insert("label".to_string(), label);

        let schema = SchemaDefinition::new("s");
        let mut out = String::new();
        render_class(&mut out, "Question", &def, &schema);

        assert!(out.contains("pub struct Question"));
        assert!(out.contains("/// A scientific question."));
        assert!(out.contains("/// Human-readable label."));
        assert!(out.contains("pub label: String,"));
    }

    #[test]
    fn render_class_renames_camelcase_to_snake_case_with_serde_rename() {
        let mut def = ClassDefinition::new("Entity");
        let mut slot = SlotDefinition::new("wasGeneratedBy");
        slot.range = Some("string".to_string());
        def.attributes.insert("wasGeneratedBy".to_string(), slot);

        let schema = SchemaDefinition::new("s");
        let mut out = String::new();
        render_class(&mut out, "Entity", &def, &schema);

        assert!(out.contains("pub was_generated_by: Option<String>,"));
        assert!(out.contains(r#"rename = "wasGeneratedBy""#));
        assert!(out.contains(r#"skip_serializing_if = "Option::is_none""#));
    }

    #[test]
    fn render_class_skips_serializing_empty_vecs() {
        let mut def = ClassDefinition::new("Entity");
        let mut slot = SlotDefinition::new("tags");
        slot.range = Some("string".to_string());
        slot.multivalued = true;
        def.attributes.insert("tags".to_string(), slot);

        let schema = SchemaDefinition::new("s");
        let mut out = String::new();
        render_class(&mut out, "Entity", &def, &schema);

        assert!(out.contains("pub tags: Vec<String>,"));
        assert!(out.contains(r#"skip_serializing_if = "Vec::is_empty""#));
    }

    #[test]
    fn render_class_resolves_global_slot_reference() {
        let mut schema = SchemaDefinition::new("s");
        let mut global = SlotDefinition::new("name");
        global.range = Some("string".to_string());
        global.required = true;
        schema.slots.insert("name".to_string(), global);

        let mut def = ClassDefinition::new("Person");
        def.slots.push("name".to_string());

        let mut out = String::new();
        render_class(&mut out, "Person", &def, &schema);
        assert!(out.contains("pub name: String,"));
    }

    #[test]
    fn render_class_marks_abstract_in_docs() {
        let mut def = ClassDefinition::new("Entity");
        def.r#abstract = true;
        let schema = SchemaDefinition::new("s");
        let mut out = String::new();
        render_class(&mut out, "Entity", &def, &schema);
        assert!(out.contains("LinkML abstract class"));
    }

    // ----- full-file rendering ----------------------------------------

    /// Build a small fixture covering: one enum, one class with each
    /// primitive range + required/optional/multivalued + camelCase rename.
    fn fixture_schema() -> SchemaDefinition {
        let mut schema = SchemaDefinition::new("demo");
        schema.version = Some("0.1.0".to_string());

        // Enum: Color with two variants.
        let mut color = EnumDefinition::new("Color");
        color.description = Some("Allowed colors.".to_string());
        color.permissible_values.insert("Red".to_string(), {
            let mut v = PermissibleValue::new("Red");
            v.description = Some("The color red.".to_string());
            v
        });
        color
            .permissible_values
            .insert("Blue".to_string(), PermissibleValue::new("Blue"));
        schema.enums.insert("Color".to_string(), color);

        // Class: Sample with one of each primitive + a class ref.
        let mut sample = ClassDefinition::new("Sample");
        sample.description = Some("A test class exercising every primitive range.".to_string());

        let mut required_string = SlotDefinition::new("name");
        required_string.range = Some("string".to_string());
        required_string.required = true;
        required_string.description = Some("The sample's name.".to_string());
        sample
            .attributes
            .insert("name".to_string(), required_string);

        let mut optional_int = SlotDefinition::new("count");
        optional_int.range = Some("integer".to_string());
        sample.attributes.insert("count".to_string(), optional_int);

        let mut bool_slot = SlotDefinition::new("active");
        bool_slot.range = Some("boolean".to_string());
        bool_slot.required = true;
        sample.attributes.insert("active".to_string(), bool_slot);

        let mut float_slot = SlotDefinition::new("ratio");
        float_slot.range = Some("float".to_string());
        sample.attributes.insert("ratio".to_string(), float_slot);

        let mut datetime_slot = SlotDefinition::new("createdAt");
        datetime_slot.range = Some("datetime".to_string());
        datetime_slot.required = true;
        sample
            .attributes
            .insert("createdAt".to_string(), datetime_slot);

        let mut multivalued_string = SlotDefinition::new("tags");
        multivalued_string.range = Some("string".to_string());
        multivalued_string.multivalued = true;
        sample
            .attributes
            .insert("tags".to_string(), multivalued_string);

        let mut color_ref = SlotDefinition::new("color");
        color_ref.range = Some("Color".to_string());
        sample.attributes.insert("color".to_string(), color_ref);

        schema.classes.insert("Sample".to_string(), sample);

        schema
    }

    #[test]
    fn fixture_renders_as_syntactically_valid_rust() {
        let schema = fixture_schema();
        let body = RustWriter::new().render(&schema);
        // `syn::parse_file` confirms the writer emits well-formed Rust
        // source. It does not check semantics — referenced types
        // existing, imports resolving, derives being satisfiable —
        // those are caught by an actual `cargo build` against a real
        // schema in a downstream consumer.
        syn::parse_file(&body)
            .unwrap_or_else(|e| panic!("generated Rust failed to parse: {e}\n---\n{body}"));
    }

    #[test]
    fn fixture_includes_all_expected_field_types() {
        let schema = fixture_schema();
        let body = RustWriter::new().render(&schema);
        assert!(body.contains("pub name: String,"));
        assert!(body.contains("pub count: Option<i64>,"));
        assert!(body.contains("pub active: bool,"));
        assert!(body.contains("pub ratio: Option<f64>,"));
        assert!(body.contains("pub created_at: chrono::DateTime<chrono::Utc>,"));
        assert!(body.contains("pub tags: Vec<String>,"));
        assert!(body.contains("pub color: Option<Color>,"));
    }

    #[test]
    fn fixture_is_idempotent() {
        // Two renders of the same SchemaDefinition must produce
        // byte-identical output. Guards against accidental
        // non-determinism (e.g. swapping a `BTreeMap` to a `HashMap`).
        let schema = fixture_schema();
        let writer = RustWriter::new();
        assert_eq!(writer.render(&schema), writer.render(&schema));
    }

    // ----- header + Writer trait surface ------------------------------

    #[test]
    fn renders_generated_marker_with_panschema_version() {
        let mut schema = SchemaDefinition::new("demo");
        schema.version = Some("0.1.0".to_string());

        let out = RustWriter::new().render(&schema);
        let expected_version = env!("CARGO_PKG_VERSION");
        assert!(
            out.contains(&format!("// @generated by panschema v{expected_version}")),
            "missing generated marker; got:\n{out}"
        );
        assert!(out.contains("// Schema: demo"));
        assert!(out.contains("// Schema version: 0.1.0"));
    }

    #[test]
    fn omits_schema_version_line_when_unspecified() {
        let schema = SchemaDefinition::new("demo");
        let out = RustWriter::new().render(&schema);
        assert!(!out.contains("// Schema version:"), "got: {out}");
    }

    #[test]
    fn format_id_is_rust() {
        assert_eq!(RustWriter::new().format_id(), "rust");
    }

    #[test]
    fn write_creates_parent_dirs() {
        let tmp = tempfile::tempdir().unwrap();
        let target = tmp.path().join("nested").join("dir").join("out.rs");
        let schema = SchemaDefinition::new("demo");

        RustWriter::new().write(&schema, &target).unwrap();
        assert!(target.exists());
        let body = std::fs::read_to_string(&target).unwrap();
        assert!(body.contains("@generated by panschema"));
    }
}
