# University Domain Schema
# A sample LinkML schema demonstrating class hierarchies and relationships
# for use with panschema graph visualization.

name: university_schema
id: https://example.org/university
title: University Domain Schema
description: |
  A schema for modeling university entities including people,
  courses, and departments. Demonstrates class hierarchies and
  relationships suitable for force graph visualization.
version: "1.0.0"
license: https://creativecommons.org/licenses/by/4.0/
created: "2026-01-31"
modified: "2026-01-31"

prefixes:
  linkml: https://w3id.org/linkml/
  uni: https://example.org/university/
  schema: http://schema.org/

default_range: string

classes:
  # Base class for all university entities
  NamedEntity:
    name: NamedEntity
    description: Base class for entities with a name
    abstract: true
    attributes:
      id:
        name: id
        description: Unique identifier
        identifier: true
        range: string
        required: true
      name:
        name: name
        description: Human-readable name
        range: string
        required: true

  # Person hierarchy
  Person:
    name: Person
    description: A person affiliated with the university
    is_a: NamedEntity
    attributes:
      email:
        name: email
        description: Email address
        range: string
      department:
        name: department
        description: Primary department affiliation
        range: Department

  Student:
    name: Student
    description: A person enrolled in courses
    is_a: Person
    attributes:
      enrolled_courses:
        name: enrolled_courses
        description: Courses the student is taking
        range: Course
        multivalued: true
      year:
        name: year
        description: Year of study
        range: YearEnum

  Faculty:
    name: Faculty
    description: A person who teaches courses
    is_a: Person
    attributes:
      teaches:
        name: teaches
        description: Courses taught by this faculty member
        range: Course
        multivalued: true
      rank:
        name: rank
        description: Academic rank
        range: RankEnum

  Staff:
    name: Staff
    description: Non-teaching personnel
    is_a: Person
    attributes:
      role:
        name: role
        description: Staff role
        range: string

  # Academic units
  Department:
    name: Department
    description: An academic department
    is_a: NamedEntity
    attributes:
      head:
        name: head
        description: Department head
        range: Faculty
      faculty:
        name: faculty
        description: Faculty members in this department
        range: Faculty
        multivalued: true
      courses:
        name: courses
        description: Courses offered by this department
        range: Course
        multivalued: true

  Course:
    name: Course
    description: An academic course
    is_a: NamedEntity
    attributes:
      code:
        name: code
        description: Course code (e.g., CS101)
        range: string
        required: true
      credits:
        name: credits
        description: Number of credit hours
        range: integer
      prerequisites:
        name: prerequisites
        description: Courses required before taking this one
        range: Course
        multivalued: true
      instructor:
        name: instructor
        description: Primary instructor
        range: Faculty

  # Research entities
  ResearchGroup:
    name: ResearchGroup
    description: A group conducting research
    is_a: NamedEntity
    attributes:
      lead:
        name: lead
        description: Research group leader
        range: Faculty
      members:
        name: members
        description: Group members
        range: Person
        multivalued: true
      topics:
        name: topics
        description: Research topics
        range: string
        multivalued: true

slots:
  identifier:
    name: identifier
    description: A unique identifier for any entity
    identifier: true
    range: string

enums:
  YearEnum:
    name: YearEnum
    description: Academic year levels
    permissible_values:
      freshman:
        text: freshman
        description: First year student
      sophomore:
        text: sophomore
        description: Second year student
      junior:
        text: junior
        description: Third year student
      senior:
        text: senior
        description: Fourth year student
      graduate:
        text: graduate
        description: Graduate student

  RankEnum:
    name: RankEnum
    description: Academic faculty ranks
    permissible_values:
      assistant_professor:
        text: assistant_professor
        description: Entry-level tenure-track
      associate_professor:
        text: associate_professor
        description: Mid-level tenured
      professor:
        text: professor
        description: Full professor
      emeritus:
        text: emeritus
        description: Retired with honors

types:
  email_type:
    name: email_type
    description: An email address
    typeof_: string
